define([], function () {
  return {
    "PropertyPaneDescription": "Configure how the approvals panel loads and prioritizes items.",
    "BasicGroupName": "Settings",
    "TitleFieldLabel": "Title",
    "DescriptionFieldLabel": "Description",
    "DataSourceTypeLabel": "Approval source",
    "DataSourceTypeApprovals": "Approvals",
    "DataSourceTypeSharePointList": "SharePoint list",
    "DataSourceTypeJsonUrl": "JSON URL",
    "SourceUrlFieldLabel": "Source URL",
    "ListTitleOrUrlFieldLabel": "List title or URL",
    "ShowCompletedFieldLabel": "Show completed approvals",
    "MaxItemsFieldLabel": "Maximum items",
    "DefaultSortFieldLabel": "Default sorting",
    "DefaultSortDueDate": "Due date",
    "DefaultSortCreatedDate": "Created date",
    "DefaultSortSource": "Source",
    "SummaryTitle": "Approval summary",
    "SummaryOverdue": "Overdue",
    "SummaryToday": "Today",
    "SummaryUpcoming": "Upcoming",
    "SummaryNoDate": "No date",
    "LoadingMessage": "Loading your approvals...",
    "EmptyMessage": "You have no visible pending approvals.",
    "PartialDataMessage": "Some approval fields are missing, so the list is being shown with partial data.",
    "ErrorMessage": "We could not load your approvals.",
    "RetryLabel": "Retry",
    "OpenDetailLabel": "Open approval",
    "RequesterLabel": "Requester",
    "SourceLabel": "Source",
    "DueDateLabel": "Due date",
    "StatusLabel": "Status",
    "OverdueLabel": "Overdue",
    "TodayLabel": "Today",
    "UpcomingLabel": "Upcoming",
    "NoDateLabel": "No date",
    "CompletedLabel": "Completed",
    "PendingLabel": "Pending",
    "UnknownLabel": "Unknown",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as a SharePoint web part.",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as a Microsoft Teams app.",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com.",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook.",
    "AppSharePointEnvironment": "The app is running on a SharePoint page.",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams.",
    "AppOfficeEnvironment": "The app is running in office.com.",
    "AppOutlookEnvironment": "The app is running in Outlook.",
    "UnknownEnvironment": "The app is running in an unknown environment.",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
