define([], function () {
  return {
    "PropertyPaneDescription": "Configura cómo se cargan y priorizan las aprobaciones.",
    "BasicGroupName": "Configuración",
    "TitleFieldLabel": "Título",
    "DescriptionFieldLabel": "Descripción",
    "DataSourceTypeLabel": "Origen de aprobaciones",
    "DataSourceTypeApprovals": "Approvals",
    "DataSourceTypeSharePointList": "Lista de SharePoint",
    "DataSourceTypeJsonUrl": "URL JSON",
    "SourceUrlFieldLabel": "URL de origen",
    "ListTitleOrUrlFieldLabel": "Título o URL de la lista",
    "ShowCompletedFieldLabel": "Mostrar aprobaciones completadas",
    "MaxItemsFieldLabel": "Máximo de elementos",
    "DefaultSortFieldLabel": "Ordenación por defecto",
    "DefaultSortDueDate": "Fecha de vencimiento",
    "DefaultSortCreatedDate": "Fecha de creación",
    "DefaultSortSource": "Origen",
    "SummaryTitle": "Resumen de aprobaciones",
    "SummaryOverdue": "Vencidas",
    "SummaryToday": "Hoy",
    "SummaryUpcoming": "Próximas",
    "SummaryNoDate": "Sin fecha",
    "LoadingMessage": "Cargando tus aprobaciones...",
    "EmptyMessage": "No tienes aprobaciones pendientes visibles.",
    "PartialDataMessage": "Faltan algunos campos de aprobación, por lo que la lista se muestra con datos parciales.",
    "ErrorMessage": "No se han podido cargar tus aprobaciones.",
    "RetryLabel": "Reintentar",
    "OpenDetailLabel": "Abrir aprobación",
    "RequesterLabel": "Solicitante",
    "SourceLabel": "Origen",
    "DueDateLabel": "Fecha límite",
    "StatusLabel": "Estado",
    "OverdueLabel": "Vencida",
    "TodayLabel": "Hoy",
    "UpcomingLabel": "Próxima",
    "NoDateLabel": "Sin fecha",
    "CompletedLabel": "Completada",
    "PendingLabel": "Pendiente",
    "UnknownLabel": "Desconocido",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint.",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams.",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com.",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook.",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint.",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams.",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com.",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook.",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido.",
    "ErrorBoundaryTitle": "Algo ha fallado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error inesperado. Recarga la página o contacta con el administrador."
  };
});
