export const mockStartARequestStrings = {
  PropertyPaneDescription: 'Request launcher settings',
  BasicGroupName: 'Catalog source',
  DataSourceTypeFieldLabel: 'Catalog source type',
  DataSourceTypeSharePointList: 'SharePoint list',
  DataSourceTypeJsonUrl: 'JSON URL',
  DataSourceTypeStaticConfig: 'Static catalog',
  ListTitleOrUrlFieldLabel: 'List title or source URL',
  ListTitleOrUrlFieldPlaceholder: 'RequestsCatalogList or /sites/hr/requests/AllItems.aspx',
  DefaultCategoryFieldLabel: 'Default category',
  DefaultCategoryFieldPlaceholder: 'Optional default filter',
  ShowPrerequisitesFieldLabel: 'Show prerequisites',
  WebPartTitle: 'Start a request',
  WebPartSubtitle: 'Quick access to common corporate processes.',
  WebPartEyebrow: 'Process launcher',
  AllCategoriesLabel: 'All',
  CategoryFilterLabel: 'Filter by category',
  CategoryFilterAriaLabel: 'Filter requests by category',
  RequestGridAriaLabel: 'Catalog of request cards',
  FeaturedBadgeLabel: 'Featured',
  PrerequisitesLabel: 'Prerequisites',
  OpenRequestLabel: 'Open request',
  NoLinkMessage: 'This request is not actionable yet.',
  LoadingMessage: 'Loading the request catalog...',
  PartialDataTitle: 'Partial data',
  PartialDataMessage: 'Some cards are missing descriptions, prerequisites or links.',
  ReadyStateLabel: 'Ready',
  EmptyTitle: 'No requests configured',
  EmptyMessage: 'Add requests to the catalog list or provide a same-origin JSON source.',
  ErrorMessage: 'The request catalog could not be loaded.',
  FooterNote: 'If a request does not have a primary link, it is shown as informational only.',
  ErrorBoundaryTitle: 'Something went wrong',
  ErrorBoundaryMessage: 'This web part encountered an unexpected error. Please reload the page or contact your administrator.'
};
