define([], function() {
  return {
    "PropertyPaneDescription": "Configure the editorial summary shown on the page.",
    "BasicGroupName": "Summary configuration",
    "TitleFieldLabel": "Web part title",
    "DescriptionFieldLabel": "Supporting copy",
    "SitePagesListFieldLabel": "Pages library or list",
    "MaxItemsFieldLabel": "Maximum number of news items",
    "FeaturedFirstFieldLabel": "Visually highlight the most recent article",
    "ToggleOnLabel": "Yes",
    "ToggleOffLabel": "No",
    "DefaultTitle": "News summary",
    "DefaultDescription": "Stay on top of the latest updates without opening a full feed.",
    "LoadingMessage": "Loading featured news",
    "ErrorMessage": "Published news could not be loaded.",
    "EmptyMessage": "There is no news available for this configuration.",
    "PartialDataMessage": "Some news items are displayed with incomplete metadata.",
    "RetryButtonLabel": "Retry",
    "OpenNewsButton": "Open article",
    "FeaturedBadgeLabel": "Featured",
    "PartialBadgeLabel": "Partial",
    "PublishedOnLabel": "Published",
    "ResultsCounterLabel": "news items",
    "MissingSummaryLabel": "This article does not include editorial summary text.",
    "MissingLinkLabel": "This article does not expose a safe link to open it.",
    "AppLocalEnvironmentSharePoint": "The app is running in your local environment as a SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running in your local environment as a Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running in your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running in your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on a SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
