define([], function() {
  return {
    "PropertyPaneDescription": "Configura el resumen editorial que se mostrará en la página.",
    "BasicGroupName": "Configuración del resumen",
    "TitleFieldLabel": "Título del web part",
    "DescriptionFieldLabel": "Texto de apoyo",
    "SitePagesListFieldLabel": "Biblioteca o lista de páginas",
    "MaxItemsFieldLabel": "Número máximo de noticias",
    "FeaturedFirstFieldLabel": "Destacar visualmente la noticia más reciente",
    "ToggleOnLabel": "Sí",
    "ToggleOffLabel": "No",
    "DefaultTitle": "Resumen de noticias",
    "DefaultDescription": "Sigue el pulso informativo sin salir de la portada ni perder tiempo en búsquedas.",
    "LoadingMessage": "Cargando noticias destacadas",
    "ErrorMessage": "No se han podido cargar las noticias publicadas.",
    "EmptyMessage": "No hay noticias disponibles para esta configuración.",
    "PartialDataMessage": "Algunas noticias se muestran con metadatos incompletos. Se mantiene la lectura degradada sin romper la experiencia.",
    "RetryButtonLabel": "Reintentar",
    "OpenNewsButton": "Abrir noticia",
    "FeaturedBadgeLabel": "Destacada",
    "PartialBadgeLabel": "Parcial",
    "PublishedOnLabel": "Publicado",
    "ResultsCounterLabel": "noticias",
    "MissingSummaryLabel": "Esta noticia no incluye extracto editorial.",
    "MissingLinkLabel": "La noticia no dispone de enlace seguro para abrirse.",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
