module.exports = {
  PropertyPaneDescription: 'Configure approvals',
  BasicGroupName: 'Settings',
  TitleFieldLabel: 'Title',
  DescriptionFieldLabel: 'Description',
  DataSourceTypeLabel: 'Approval source',
  DataSourceTypeApprovals: 'Approvals',
  DataSourceTypeSharePointList: 'SharePoint list',
  DataSourceTypeJsonUrl: 'JSON URL',
  SourceUrlFieldLabel: 'Source URL',
  ListTitleOrUrlFieldLabel: 'List title or URL',
  ShowCompletedFieldLabel: 'Show completed approvals',
  MaxItemsFieldLabel: 'Maximum items',
  DefaultSortFieldLabel: 'Default sorting',
  DefaultSortDueDate: 'Due date',
  DefaultSortCreatedDate: 'Created date',
  DefaultSortSource: 'Source',
  SummaryTitle: 'Approval summary',
  SummaryOverdue: 'Overdue',
  SummaryToday: 'Today',
  SummaryUpcoming: 'Upcoming',
  SummaryNoDate: 'No date',
  LoadingMessage: 'Loading your approvals...',
  EmptyMessage: 'You have no visible pending approvals.',
  PartialDataMessage: 'Some approval fields are missing.',
  ErrorMessage: 'We could not load your approvals.',
  RetryLabel: 'Retry',
  OpenDetailLabel: 'Open approval',
  RequesterLabel: 'Requester',
  SourceLabel: 'Source',
  DueDateLabel: 'Due date',
  StatusLabel: 'Status',
  OverdueLabel: 'Overdue',
  TodayLabel: 'Today',
  UpcomingLabel: 'Upcoming',
  NoDateLabel: 'No date',
  CompletedLabel: 'Completed',
  PendingLabel: 'Pending',
  UnknownLabel: 'Unknown',
  AppLocalEnvironmentSharePoint: 'Local SharePoint',
  AppLocalEnvironmentTeams: 'Local Teams',
  AppLocalEnvironmentOffice: 'Local Office',
  AppLocalEnvironmentOutlook: 'Local Outlook',
  AppSharePointEnvironment: 'SharePoint',
  AppTeamsTabEnvironment: 'Teams',
  AppOfficeEnvironment: 'Office',
  AppOutlookEnvironment: 'Outlook',
  UnknownEnvironment: 'Unknown environment',
  ErrorBoundaryTitle: 'Something went wrong',
  ErrorBoundaryMessage: 'Unexpected error'
};
