define([], function() {
  return {
    "PropertyPaneDescription": "Configura el feed de noticias específico para una área, departamento o página temática.",
    "BasicGroupName": "Configuración del feed",
    "TitleFieldLabel": "Título del web part",
    "DescriptionFieldLabel": "Texto de apoyo",
    "AreaFilterFieldLabel": "Área o etiqueta a filtrar",
    "SitePagesListFieldLabel": "Biblioteca o lista de páginas",
    "MaxItemsFieldLabel": "Número máximo de noticias",
    "ShowImageFieldLabel": "Mostrar imagen principal",
    "FeaturedFirstFieldLabel": "Destacar la noticia más reciente",
    "ToggleOnLabel": "Sí",
    "ToggleOffLabel": "No",
    "DefaultTitle": "Noticias por área",
    "DefaultDescription": "Muestra solo las noticias que encajan con el contexto del área y evita ruido informativo.",
    "LoadingMessage": "Cargando noticias del área",
    "ErrorMessage": "No se han podido cargar las noticias del área.",
    "EmptyMessage": "No hay noticias disponibles para esta área.",
    "PartialDataMessage": "Algunas noticias llegan con metadatos incompletos. Se muestran de forma degradada sin romper la experiencia.",
    "RetryButtonLabel": "Reintentar",
    "OpenNewsButton": "Abrir noticia",
    "FeaturedBadgeLabel": "Destacada",
    "PartialBadgeLabel": "Parcial",
    "PublishedOnLabel": "Publicado",
    "ResultsCounterLabel": "noticias",
    "MissingSummaryLabel": "Esta noticia no incluye extracto editorial.",
    "MissingLinkLabel": "La noticia no dispone de enlace seguro para abrirse.",
    "AllAreasLabel": "Todas las áreas",
    "TagsLabel": "Etiquetas de la noticia",
    "FilterLabel": "Filtro:",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
