define([], function() {
  return {
    "PropertyPaneDescription": "Configure the express directory and its people sources.",
    "BasicGroupName": "Configuration",
    "DescriptionFieldLabel": "Web part subtitle",
    "DataSourceTypesFieldLabel": "Data sources",
    "DataSourceTypesDescription": "Comma-separated list. Supported values: Directory, SharePointList, JsonUrl, StaticConfig.",
    "ListTitleOrUrlFieldLabel": "SharePoint list or same-origin URL",
    "ListTitleOrUrlDescription": "Supports a list title or a /Forms/AllItems.aspx view URL.",
    "JsonUrlFieldLabel": "Same-origin JSON URL",
    "JsonUrlDescription": "Optional JSON source for curated people data.",
    "StaticPeopleJsonFieldLabel": "Static people JSON",
    "StaticPeopleJsonDescription": "Optional. Paste a JSON array or an object with an items array.",
    "MaxItemsFieldLabel": "Maximum number of people",
    "DefaultAreaFilterFieldLabel": "Default area filter",
    "DefaultAreaFilterDescription": "Applied on load when a matching area exists.",
    "WebPartTitle": "Express directory",
    "WebPartSubtitle": "Find people by name, role, area, or basic contact info.",
    "SearchLabel": "Search",
    "SearchPlaceholder": "Search by name, title, area, or email",
    "SearchSummaryLabel": "Search prioritizes exact name matches.",
    "AreaFilterLabel": "Filter by area",
    "AllAreasOption": "All areas",
    "LoadingLabel": "Loading directory...",
    "RefreshButton": "Refresh",
    "ResultsCountLabel": "people visible",
    "PartialDataBadgeLabel": "Partial data",
    "PartialDataMessage": "Some people are missing a photo, profile, title, or complete area.",
    "EmptyStateTitle": "No people to show",
    "EmptyStateMessage": "Try changing the search term or area filter.",
    "ErrorStateTitle": "Could not load the directory",
    "ErrorStateMessage": "Check the data source configuration and try again.",
    "ContactEmailLabel": "Send email",
    "ContactProfileLabel": "Open profile",
    "NoRoleLabel": "No title",
    "NoAreaLabel": "No area",
    "NoPhotoLabel": "No photo",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  }
});
