define([], function() {
  return {
    "PropertyPaneDescription": "Configura el directorio express y sus orígenes de personas.",
    "BasicGroupName": "Configuración",
    "DescriptionFieldLabel": "Subtítulo de la web part",
    "DataSourceTypesFieldLabel": "Orígenes de datos",
    "DataSourceTypesDescription": "Lista separada por comas. Valores admitidos: Directory, SharePointList, JsonUrl, StaticConfig.",
    "ListTitleOrUrlFieldLabel": "Lista SharePoint o URL same-origin",
    "ListTitleOrUrlDescription": "Se admite título de lista o URL de vista /Forms/AllItems.aspx.",
    "JsonUrlFieldLabel": "URL JSON same-origin",
    "JsonUrlDescription": "Origen opcional en JSON para personas curadas.",
    "StaticPeopleJsonFieldLabel": "JSON estático de personas",
    "StaticPeopleJsonDescription": "Opcional. Pega un array JSON o un objeto con la clave items.",
    "MaxItemsFieldLabel": "Número máximo de personas",
    "DefaultAreaFilterFieldLabel": "Filtro de área por defecto",
    "DefaultAreaFilterDescription": "Se aplicará al abrir la web part si existe coincidencia.",
    "WebPartTitle": "Directorio express",
    "WebPartSubtitle": "Localiza personas por nombre, rol, área o contacto básico.",
    "SearchLabel": "Buscar",
    "SearchPlaceholder": "Buscar por nombre, cargo, área o correo",
    "SearchSummaryLabel": "La búsqueda prioriza coincidencias exactas de nombre.",
    "AreaFilterLabel": "Filtrar por área",
    "AllAreasOption": "Todas las áreas",
    "LoadingLabel": "Cargando directorio...",
    "RefreshButton": "Refrescar",
    "ResultsCountLabel": "personas visibles",
    "PartialDataBadgeLabel": "Datos parciales",
    "PartialDataMessage": "Algunas personas no tienen foto, perfil, cargo o área completa.",
    "EmptyStateTitle": "No hay personas para mostrar",
    "EmptyStateMessage": "Prueba a cambiar la búsqueda o el filtro de área.",
    "ErrorStateTitle": "No se ha podido cargar el directorio",
    "ErrorStateMessage": "Revisa la configuración de los orígenes de datos y vuelve a intentarlo.",
    "ContactEmailLabel": "Enviar correo",
    "ContactProfileLabel": "Abrir perfil",
    "NoRoleLabel": "Sin cargo",
    "NoAreaLabel": "Sin área",
    "NoPhotoLabel": "Sin foto",
    "AppLocalEnvironmentSharePoint": "La app se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La app se está ejecutando en tu entorno local como app de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La app se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La app se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La app se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La app se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La app se está ejecutando en office.com",
    "AppOutlookEnvironment": "La app se está ejecutando en Outlook",
    "UnknownEnvironment": "La app se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  }
});
