define([], function() {
  return {
    "PropertyPaneDescription": "Configure the featured question",
    "WebPartTitle": "Featured question",
    "PropertyPaneGeneralGroupName": "Configuration",
    "DataSourceFieldLabel": "Data source",
    "DataSourceSharePointListLabel": "SharePoint list",
    "DataSourceJsonUrlLabel": "JSON URL",
    "DataSourceStaticConfigLabel": "Static configuration",
    "ListTitleOrUrlFieldLabel": "List title or URL",
    "ShowVotesFieldLabel": "Show votes",
    "ToggleOnLabel": "Yes",
    "ToggleOffLabel": "No",
    "LoadingMessage": "Loading featured question...",
    "EmptyMessage": "There is no active featured question.",
    "ErrorMessage": "The featured question could not be loaded.",
    "PartialDataMessage": "The question was loaded with partial data.",
    "QuestionOfTheDayLabel": "Editorial focus",
    "SelectAnswerLabel": "Select your answer",
    "QuestionFromLabel": "Question from",
    "VotesLabel": "votes",
    "ExpiresLabel": "Valid until",
    "AppLocalEnvironmentSharePoint": "Running on SharePoint",
    "AppLocalEnvironmentTeams": "Running on Teams",
    "AppSharePointEnvironment": "Running on SharePoint",
    "UnknownEnvironment": "Unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
