define([], function() {
  return {
    "PropertyPaneDescription": "Configura la pregunta destacada",
    "WebPartTitle": "Pregunta destacada",
    "PropertyPaneGeneralGroupName": "Configuración",
    "DataSourceFieldLabel": "Tipo de origen",
    "DataSourceSharePointListLabel": "Lista de SharePoint",
    "DataSourceJsonUrlLabel": "URL JSON",
    "DataSourceStaticConfigLabel": "Configuración estática",
    "ListTitleOrUrlFieldLabel": "Título o URL de lista",
    "ShowVotesFieldLabel": "Mostrar votos",
    "ToggleOnLabel": "Sí",
    "ToggleOffLabel": "No",
    "LoadingMessage": "Cargando pregunta destacada...",
    "EmptyMessage": "No hay ninguna pregunta destacada activa.",
    "ErrorMessage": "No se ha podido cargar la pregunta destacada.",
    "PartialDataMessage": "La pregunta se ha cargado con datos parciales.",
    "QuestionOfTheDayLabel": "Foco editorial",
    "SelectAnswerLabel": "Selecciona tu respuesta",
    "QuestionFromLabel": "Pregunta de",
    "VotesLabel": "votos",
    "ExpiresLabel": "Válida hasta",
    "AppLocalEnvironmentSharePoint": "Ejecutándose en SharePoint",
    "AppLocalEnvironmentTeams": "Ejecutándose en Teams",
    "AppSharePointEnvironment": "Ejecutándose en SharePoint",
    "UnknownEnvironment": "Entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
