define([], function() {
  return {
    "PropertyPaneDescription": "Configure the birthdays and anniversaries panel and data source.",
    "BasicGroupName": "Configuration",
    "DescriptionFieldLabel": "Description",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "PropertyPaneDataGroupName": "Data source",
    "PropertyPaneBehaviorGroupName": "Behavior",
    "DataSourceTypesLabel": "Source types",
    "DataSourceTypesDescription": "Allowed values: Directory, SharePointList, JsonUrl",
    "DirectoryJsonUrlLabel": "Directory JSON URL",
    "DirectoryJsonUrlDescription": "Same-origin source for the directory feed.",
    "ListTitleOrUrlLabel": "List title or URL",
    "ListTitleOrUrlDescription": "Accepts a list title or a same-origin view URL.",
    "JsonUrlLabel": "Alternative JSON URL",
    "JsonUrlDescription": "Same-origin source for direct JSON payloads.",
    "ShowBirthdaysText": "Show birthdays",
    "ShowAnniversariesText": "Show anniversaries",
    "DaysAheadLabel": "Days ahead",
    "DaysAheadDescription": "Time window for upcoming celebrations.",
    "WebPartTitle": "Birthdays and anniversaries",
    "WebPartSubtitle": "Highlight today's milestones and the next ones in a light, readable view.",
    "LoadingLabel": "Loading celebrations",
    "SourceLabel": "Source",
    "SourceUnavailableLabel": "Source not confirmed",
    "TodaySectionTitle": "Today",
    "UpcomingSectionTitle": "Upcoming",
    "PartialSectionTitle": "Partial data",
    "ErrorStateTitle": "Celebrations could not be loaded",
    "ErrorStateMessage": "Review the configured source and try again.",
    "ErrorStateMessageDetailed": "Loading failed. Review the configured source and try again.",
    "ErrorStateRetryAction": "Retry",
    "EmptyStateTitle": "There are no upcoming celebrations",
    "EmptyStateMessage": "There are no milestones inside the configured window.",
    "PartialEmptyStateTitle": "Only partial information is available",
    "PartialEmptyStateMessage": "Some records are incomplete and are still visible as a partial reference.",
    "RefreshAction": "Refresh",
    "PartialBannerMessage": "Some records were normalized with partial data. The view is still usable.",
    "CardTodayBadge": "Today",
    "CardBirthdayBadge": "Birthday",
    "CardAnniversaryBadge": "Anniversary",
    "CardPartialBadge": "Partial data",
    "CardTodayMessage": "Celebration is today",
    "CardPendingDateMessage": "Date pending validation",
    "CardDaysRemainingFormat": "{0} days remaining",
    "CardPartialFootnote": "Partial information normalized to keep the milestone visible.",
    "CardCompleteFootnote": "Complete information.",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
