define([], function() {
  return {
    "PropertyPaneDescription": "Configura el panel de cumpleaños y aniversarios y el origen de datos.",
    "BasicGroupName": "Configuración",
    "DescriptionFieldLabel": "Descripción",
    "AppLocalEnvironmentSharePoint": "La app se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La app se está ejecutando en tu entorno local como app de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La app se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La app se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La app se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La app se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La app se está ejecutando en office.com",
    "AppOutlookEnvironment": "La app se está ejecutando en Outlook",
    "UnknownEnvironment": "La app se está ejecutando en un entorno desconocido",
    "PropertyPaneDataGroupName": "Origen de datos",
    "PropertyPaneBehaviorGroupName": "Comportamiento",
    "DataSourceTypesLabel": "Tipos de origen",
    "DataSourceTypesDescription": "Valores permitidos: Directory, SharePointList, JsonUrl",
    "DirectoryJsonUrlLabel": "URL JSON de directorio",
    "DirectoryJsonUrlDescription": "Origen same-origin para el feed de directorio.",
    "ListTitleOrUrlLabel": "Titulo o URL de la lista",
    "ListTitleOrUrlDescription": "Acepta titulo de lista o URL de vista same-origin.",
    "JsonUrlLabel": "URL JSON alternativa",
    "JsonUrlDescription": "Origen same-origin para cargas JSON directas.",
    "ShowBirthdaysText": "Mostrar cumpleanos",
    "ShowAnniversariesText": "Mostrar aniversarios",
    "DaysAheadLabel": "Dias hacia adelante",
    "DaysAheadDescription": "Ventana temporal para proximas celebraciones.",
    "WebPartTitle": "Cumpleanos y aniversarios",
    "WebPartSubtitle": "Reconoce los hitos de hoy y los proximos en una vista ligera.",
    "LoadingLabel": "Cargando celebraciones",
    "SourceLabel": "Origen",
    "SourceUnavailableLabel": "Sin origen confirmado",
    "TodaySectionTitle": "Hoy",
    "UpcomingSectionTitle": "Proximos",
    "PartialSectionTitle": "Datos parciales",
    "ErrorStateTitle": "No se han podido cargar las celebraciones",
    "ErrorStateMessage": "Revisa el origen configurado y vuelve a intentarlo.",
    "ErrorStateMessageDetailed": "La carga ha fallado. Revisa el origen configurado y vuelve a intentarlo.",
    "ErrorStateRetryAction": "Reintentar",
    "EmptyStateTitle": "No hay celebraciones proximas",
    "EmptyStateMessage": "No hay hitos dentro de la ventana configurada.",
    "PartialEmptyStateTitle": "Solo hay informacion parcial disponible",
    "PartialEmptyStateMessage": "Algunos registros tienen campos incompletos y se han mantenido visibles como referencia.",
    "RefreshAction": "Actualizar",
    "PartialBannerMessage": "Algunos registros se han normalizado con datos parciales. La vista sigue siendo utilizable.",
    "CardTodayBadge": "Hoy",
    "CardBirthdayBadge": "Cumpleanos",
    "CardAnniversaryBadge": "Aniversario",
    "CardPartialBadge": "Datos parciales",
    "CardTodayMessage": "Celebracion de hoy",
    "CardPendingDateMessage": "Fecha pendiente de validar",
    "CardDaysRemainingFormat": "Faltan {0} dias",
    "CardPartialFootnote": "Informacion parcial normalizada para no ocultar el hito.",
    "CardCompleteFootnote": "Informacion completa.",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la pagina o contacta con el administrador."
  };
});
