declare interface IBirthdaysAndAnniversariesWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  AppLocalEnvironmentSharePoint: string;
  AppLocalEnvironmentTeams: string;
  AppLocalEnvironmentOffice: string;
  AppLocalEnvironmentOutlook: string;
  AppSharePointEnvironment: string;
  AppTeamsTabEnvironment: string;
  AppOfficeEnvironment: string;
  AppOutlookEnvironment: string;
  UnknownEnvironment: string;
  PropertyPaneDataGroupName: string;
  PropertyPaneBehaviorGroupName: string;
  DataSourceTypesLabel: string;
  DataSourceTypesDescription: string;
  DirectoryJsonUrlLabel: string;
  DirectoryJsonUrlDescription: string;
  ListTitleOrUrlLabel: string;
  ListTitleOrUrlDescription: string;
  JsonUrlLabel: string;
  JsonUrlDescription: string;
  ShowBirthdaysText: string;
  ShowAnniversariesText: string;
  DaysAheadLabel: string;
  DaysAheadDescription: string;
  WebPartTitle: string;
  WebPartSubtitle: string;
  LoadingLabel: string;
  SourceLabel: string;
  SourceUnavailableLabel: string;
  TodaySectionTitle: string;
  UpcomingSectionTitle: string;
  PartialSectionTitle: string;
  ErrorStateTitle: string;
  ErrorStateMessage: string;
  ErrorStateMessageDetailed: string;
  ErrorStateRetryAction: string;
  EmptyStateTitle: string;
  EmptyStateMessage: string;
  PartialEmptyStateTitle: string;
  PartialEmptyStateMessage: string;
  RefreshAction: string;
  PartialBannerMessage: string;
  CardTodayBadge: string;
  CardBirthdayBadge: string;
  CardAnniversaryBadge: string;
  CardPartialBadge: string;
  CardTodayMessage: string;
  CardPendingDateMessage: string;
  CardDaysRemainingFormat: string;
  CardPartialFootnote: string;
  CardCompleteFootnote: string;
  ErrorBoundaryTitle: string;
  ErrorBoundaryMessage: string;
}

declare module 'BirthdaysAndAnniversariesWebPartStrings' {
  const strings: IBirthdaysAndAnniversariesWebPartStrings;
  export = strings;
}
