define([], function() {
  return {
    "PropertyPaneDescription": "Configure the maintenance feed and how completed windows are shown.",
    "ContentGroupName": "Content",
    "ViewGroupName": "View",
    "TitleFieldLabel": "Title",
    "DescriptionFieldLabel": "Description",
    "DataSourceTypeFieldLabel": "Data source",
    "DataSourceTypeSharePointList": "SharePoint list",
    "DataSourceTypeJsonUrl": "Same-origin JSON",
    "ListTitleOrUrlFieldLabel": "List title or URL",
    "JsonUrlFieldLabel": "JSON URL",
    "HideCompletedFieldLabel": "Hide completed maintenance windows",
    "MaxItemsFieldLabel": "Maximum items",
    "ToggleOnLabel": "Hide",
    "ToggleOffLabel": "Show",
    "TimelineEyebrow": "Scheduled operations",
    "SourceLabel": "Source",
    "StatusUpcoming": "Upcoming",
    "StatusInProgress": "In progress",
    "StatusCompleted": "Completed",
    "StatusUnknown": "Unknown",
    "ImpactLow": "Low impact",
    "ImpactMedium": "Medium impact",
    "ImpactHigh": "High impact",
    "ImpactUnknown": "Impact pending",
    "ServicesLabel": "Affected services",
    "NoServicesLabel": "No services specified",
    "DetailButtonLabel": "Open details",
    "RetryButtonLabel": "Retry",
    "EmptyStateTitle": "No scheduled maintenance",
    "EmptyStateMessage": "There are no scheduled maintenance windows for the current filter.",
    "ErrorStateTitle": "Maintenance data could not be loaded",
    "ErrorStateMessage": "Check the configured source and try again.",
    "PartialStateTitle": "Partial maintenance data",
    "PartialStateMessage": "Some items are missing dates or impact details, but they remain visible for context.",
    "PartialBadgeLabel": "Partial",
    "UnknownDateLabel": "Date pending",
    "SummarySectionAriaLabel": "Maintenance summary",
    "InProgressSummaryLabel": "In progress",
    "UpcomingSummaryLabel": "Upcoming",
    "CompletedSummaryLabel": "Completed",
    "ReadySummaryLabel": "Ready",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
