define([], function() {
  return {
    "PropertyPaneDescription": "Configura el feed de mantenimiento y como se muestran las ventanas completadas.",
    "ContentGroupName": "Contenido",
    "ViewGroupName": "Vista",
    "TitleFieldLabel": "Titulo",
    "DescriptionFieldLabel": "Descripcion",
    "DataSourceTypeFieldLabel": "Origen de datos",
    "DataSourceTypeSharePointList": "Lista de SharePoint",
    "DataSourceTypeJsonUrl": "JSON same-origin",
    "ListTitleOrUrlFieldLabel": "Titulo o URL de la lista",
    "JsonUrlFieldLabel": "URL JSON",
    "HideCompletedFieldLabel": "Ocultar mantenimientos completados",
    "MaxItemsFieldLabel": "Maximo de elementos",
    "ToggleOnLabel": "Ocultar",
    "ToggleOffLabel": "Mostrar",
    "TimelineEyebrow": "Operacion programada",
    "SourceLabel": "Origen",
    "StatusUpcoming": "Proximo",
    "StatusInProgress": "En curso",
    "StatusCompleted": "Completado",
    "StatusUnknown": "Pendiente",
    "ImpactLow": "Impacto bajo",
    "ImpactMedium": "Impacto medio",
    "ImpactHigh": "Impacto alto",
    "ImpactUnknown": "Impacto pendiente",
    "ServicesLabel": "Servicios afectados",
    "NoServicesLabel": "Sin servicios informados",
    "DetailButtonLabel": "Abrir detalle",
    "RetryButtonLabel": "Reintentar",
    "EmptyStateTitle": "No hay mantenimientos programados",
    "EmptyStateMessage": "No hay ventanas de mantenimiento para el filtro actual.",
    "ErrorStateTitle": "No se han podido cargar los mantenimientos",
    "ErrorStateMessage": "Revisa el origen configurado y vuelve a intentarlo.",
    "PartialStateTitle": "Datos parciales de mantenimiento",
    "PartialStateMessage": "Algunos elementos no incluyen fechas o impacto completos, pero siguen visibles para no perder contexto.",
    "PartialBadgeLabel": "Parcial",
    "UnknownDateLabel": "Fecha pendiente",
    "SummarySectionAriaLabel": "Resumen de mantenimiento",
    "InProgressSummaryLabel": "En curso",
    "UpcomingSummaryLabel": "Proximos",
    "CompletedSummaryLabel": "Completados",
    "ReadySummaryLabel": "Listo",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la pagina o contacta con el administrador."
  };
});
