module.exports = {
  PropertyPaneDescription: 'Configure guides',
  BasicGroupName: 'Settings',
  TitleFieldLabel: 'Title',
  DescriptionFieldLabel: 'Description',
  DataSourceTypeFieldLabel: 'Data source',
  SharePointListOptionLabel: 'SharePoint list',
  JsonUrlOptionLabel: 'JSON URL',
  StaticConfigOptionLabel: 'Built-in sample catalog',
  ListTitleOrUrlFieldLabel: 'List title or URL',
  DefaultCategoryFieldLabel: 'Default category',
  MaxItemsFieldLabel: 'Maximum guides',
  VisibleGuidesLabel: 'Visible guides',
  CategoryFilterLabel: 'Filter by category',
  FilterAllLabel: 'All',
  LoadingMessage: 'Loading guides...',
  EmptyMessage: 'There are no guides available right now.',
  EmptyHint: 'Adjust the source.',
  PartialDataMessage: 'Some guides have incomplete data.',
  ErrorMessage: 'We could not load the guides.',
  ExpandLabel: 'Show steps',
  CollapseLabel: 'Hide steps',
  StepsHeading: 'Steps',
  RelatedLinkLabel: 'Open related resource',
  FeaturedBadgeLabel: 'Featured',
  PartialBadgeLabel: 'Partial data',
  AppLocalEnvironmentSharePoint: 'Local SharePoint',
  AppLocalEnvironmentTeams: 'Local Teams',
  AppLocalEnvironmentOffice: 'Local Office',
  AppLocalEnvironmentOutlook: 'Local Outlook',
  AppSharePointEnvironment: 'SharePoint',
  AppTeamsTabEnvironment: 'Teams',
  AppOfficeEnvironment: 'Office',
  AppOutlookEnvironment: 'Outlook',
  UnknownEnvironment: 'Unknown environment',
  ErrorBoundaryTitle: 'Something went wrong',
  ErrorBoundaryMessage: 'Unexpected error'
};
