define([], function() {
  return {
    "PropertyPaneDescription": "Configura el feed de cambios recientes mostrado en la página.",
    "BasicGroupName": "Configuración del feed",
    "TitleFieldLabel": "Título del web part",
    "DescriptionFieldLabel": "Texto de apoyo",
    "SourceKindFieldLabel": "Tipo de origen",
    "SourceKindListLabel": "Lista",
    "SourceKindLibraryLabel": "Biblioteca",
    "ListTitleFieldLabel": "Nombre de la lista o biblioteca",
    "DefaultTypeFilterFieldLabel": "Filtro de tipo por defecto",
    "MaxItemsFieldLabel": "Número máximo de elementos",
    "DefaultTitle": "Qué ha cambiado",
    "DefaultDescription": "Muestra los cambios recientes sin obligar al usuario a revisar varios espacios manualmente.",
    "LoadingMessage": "Cargando cambios recientes",
    "ErrorMessage": "No se han podido cargar los cambios recientes.",
    "EmptyMessage": "No hay cambios recientes visibles.",
    "PartialDataMessage": "Algunos elementos se muestran con metadatos parciales. El feed sigue siendo utilizable.",
    "RetryButtonLabel": "Reintentar",
    "OpenItemButton": "Abrir elemento",
    "UpdatedBadgeLabel": "Actualizado",
    "PartialBadgeLabel": "Parcial",
    "ChangedAtLabel": "Fecha",
    "ResultsCounterLabel": "elementos",
    "MissingSummaryLabel": "Este elemento no incluye resumen.",
    "MissingLinkLabel": "Este elemento no dispone de enlace para abrirse.",
    "AllTypesLabel": "Todos los tipos",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
