define([], function() {
  return {
    "PropertyPaneDescription": "Configure the shared team agenda.",
    "BasicGroupName": "Configuration",
    "TitleFieldLabel": "Title",
    "DescriptionFieldLabel": "Description",
    "DataSourceTypeFieldLabel": "Data source",
    "DataSourceCalendarLabel": "Calendar",
    "DataSourceSharePointListLabel": "SharePoint list",
    "DataSourceJsonUrlLabel": "Same-origin JSON",
    "DataSourceStaticConfigLabel": "Static configuration",
    "ListTitleOrUrlFieldLabel": "List or JSON URL",
    "MaxItemsFieldLabel": "Maximum events",
    "ShowPastFieldLabel": "Show past events",
    "DefaultTypeFilterFieldLabel": "Initial type filter",
    "DefaultWebPartTitle": "Team agenda",
    "DefaultWebPartDescription": "Upcoming meetings, demos, and milestones for the team at a glance.",
    "KickerLabel": "Shared visibility",
    "EventsCountLabel": "events",
    "FilterLabel": "Filter by type",
    "AllTypesOptionLabel": "All event types",
    "LoadingStateLabel": "Loading team agenda",
    "EmptyStateMessage": "There are no upcoming team events.",
    "PartialStateMessage": "Some events are shown with partial metadata.",
    "ErrorStateMessage": "The team agenda could not be loaded.",
    "TodayGroupLabel": "Today",
    "TomorrowGroupLabel": "Tomorrow",
    "UpcomingGroupLabel": "Upcoming",
    "PastGroupLabel": "Past",
    "PartialBadgeLabel": "Partial",
    "JoinActionLabel": "Join",
    "OpenActionLabel": "Open details",
    "DateUnavailableLabel": "Date unavailable",
    "AppLocalEnvironmentSharePoint": "The app is running in your local environment as a SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running in your local environment as a Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running in your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running in your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on a SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
