define([], function() {
  return {
    "PropertyPaneDescription": "Configura la agenda compartida del equipo.",
    "BasicGroupName": "Configuración",
    "TitleFieldLabel": "Título",
    "DescriptionFieldLabel": "Descripción",
    "DataSourceTypeFieldLabel": "Origen de datos",
    "DataSourceCalendarLabel": "Calendario",
    "DataSourceSharePointListLabel": "Lista de SharePoint",
    "DataSourceJsonUrlLabel": "JSON del mismo origen",
    "DataSourceStaticConfigLabel": "Configuración estática",
    "ListTitleOrUrlFieldLabel": "Lista o URL JSON",
    "MaxItemsFieldLabel": "Máximo de eventos",
    "ShowPastFieldLabel": "Mostrar eventos pasados",
    "DefaultTypeFilterFieldLabel": "Filtro de tipo inicial",
    "DefaultWebPartTitle": "Agenda del equipo",
    "DefaultWebPartDescription": "Próximas reuniones, demos e hitos relevantes del equipo en un vistazo.",
    "KickerLabel": "Visión compartida",
    "EventsCountLabel": "eventos",
    "FilterLabel": "Filtrar por tipo",
    "AllTypesOptionLabel": "Todos los tipos",
    "LoadingStateLabel": "Cargando agenda del equipo",
    "EmptyStateMessage": "No hay próximos eventos del equipo.",
    "PartialStateMessage": "Se muestran eventos con metadatos parciales.",
    "ErrorStateMessage": "No se ha podido cargar la agenda del equipo.",
    "TodayGroupLabel": "Hoy",
    "TomorrowGroupLabel": "Mañana",
    "UpcomingGroupLabel": "Próximos días",
    "PastGroupLabel": "Pasados",
    "PartialBadgeLabel": "Parcial",
    "JoinActionLabel": "Unirse",
    "OpenActionLabel": "Abrir detalle",
    "DateUnavailableLabel": "Fecha no disponible",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
