define([], function () {
  return {
    "PropertyPaneDescription": "Configuración del lanzador de solicitudes",
    "BasicGroupName": "Origen del catálogo",
    "DataSourceTypeFieldLabel": "Tipo de origen del catálogo",
    "DataSourceTypeSharePointList": "Lista de SharePoint",
    "DataSourceTypeJsonUrl": "URL JSON",
    "DataSourceTypeStaticConfig": "Catálogo local",
    "ListTitleOrUrlFieldLabel": "Título de lista o URL de origen",
    "ListTitleOrUrlFieldPlaceholder": "RequestsCatalogList o /sites/rrhh/requests/AllItems.aspx",
    "DefaultCategoryFieldLabel": "Categoría por defecto",
    "DefaultCategoryFieldPlaceholder": "Filtro opcional por defecto",
    "ShowPrerequisitesFieldLabel": "Mostrar prerequisitos",
    "WebPartTitle": "Inicia una solicitud",
    "WebPartSubtitle": "Accesos rápidos a procesos corporativos habituales para iniciar solicitudes sin dudar qué flujo usar.",
    "WebPartEyebrow": "Lanzador de procesos",
    "AllCategoriesLabel": "Todas",
    "CategoryFilterLabel": "Filtrar por categoría",
    "CategoryFilterAriaLabel": "Filtrar solicitudes por categoría",
    "RequestGridAriaLabel": "Catálogo de tarjetas de solicitud",
    "FeaturedBadgeLabel": "Destacada",
    "PrerequisitesLabel": "Prerequisitos",
    "OpenRequestLabel": "Abrir solicitud",
    "NoLinkMessage": "Esta solicitud todavía no es accionable.",
    "LoadingMessage": "Cargando el catálogo de solicitudes...",
    "PartialDataTitle": "Datos parciales",
    "PartialDataMessage": "Algunas tarjetas no tienen descripción, prerequisitos o enlace.",
    "ReadyStateLabel": "Listo",
    "EmptyTitle": "No hay solicitudes configuradas",
    "EmptyMessage": "Añade solicitudes a la lista del catálogo o proporciona una URL JSON del mismo origen.",
    "ErrorMessage": "No se ha podido cargar el catálogo de solicitudes.",
    "FooterNote": "Si una solicitud no tiene enlace principal, se muestra solo como informativa.",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  }
});
