define([], function() {
  return {
    "PropertyPaneDescription": "Configure the data source and answer flow for the micro survey.",
    "PropertyPaneGeneralGroupName": "General",
    "PropertyPaneSharePointGroupName": "SharePoint source",
    "PropertyPaneApiGroupName": "API source",
    "PropertyPaneStaticGroupName": "Static source",
    "DescriptionFieldLabel": "Description",
    "DataSourceFieldLabel": "Data source",
    "DataSourceSharePointListLabel": "SharePoint list",
    "DataSourceApiEndpointLabel": "API endpoint",
    "DataSourceStaticConfigLabel": "Static configuration",
    "OneResponsePerUserFieldLabel": "Limit to one answer per user",
    "ToggleOnLabel": "On",
    "ToggleOffLabel": "Off",
    "ListTitleOrUrlFieldLabel": "Question list (title or URL)",
    "ResponsesListTitleOrUrlFieldLabel": "Responses list (title or URL)",
    "ApiEndpointUrlFieldLabel": "Endpoint URL",
    "QuestionTextFieldLabel": "Static question",
    "OptionsCsvFieldLabel": "Static options",
    "WebPartEyebrow": "Lightweight participation",
    "WebPartTitle": "Micro survey",
    "WebPartSubtitle": "Capture a quick signal with a single question and one lightweight action.",
    "LoadingLabel": "Loading micro survey",
    "SourceLabel": "Source",
    "OptionsGroupLabel": "Select one option",
    "SubmitAction": "Submit answer",
    "SubmittingAction": "Submitting",
    "RefreshAction": "Refresh",
    "SuccessStateTitle": "Answer recorded",
    "SuccessStateMessage": "Your answer was stored successfully.",
    "SelectedOptionLabel": "Selected option",
    "ErrorStateTitle": "The micro survey could not be loaded",
    "ErrorStateMessage": "Review the configured source and try again.",
    "EmptyStateTitle": "There is no active question",
    "EmptyStateMessage": "Publish an active question or switch to a source with data.",
    "PartialStateTitle": "Partial information",
    "PartialStateMessage": "The question is available, but some optional fields are missing from the source.",
    "InteractionErrorTitle": "The action could not be completed",
    "SelectionRequiredMessage": "Select one option before submitting your answer.",
    "AlreadyAnsweredMessage": "You have already answered this micro survey.",
    "QuestionUnavailableMessage": "There is no valid question available to answer.",
    "SubmitErrorMessage": "The answer could not be recorded. Try again.",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
