define([], function() {
  return {
    "PropertyPaneDescription": "Configura el origen y la experiencia de respuesta de la microencuesta.",
    "PropertyPaneGeneralGroupName": "General",
    "PropertyPaneSharePointGroupName": "Origen SharePoint",
    "PropertyPaneApiGroupName": "Origen API",
    "PropertyPaneStaticGroupName": "Origen estatico",
    "DescriptionFieldLabel": "Descripcion",
    "DataSourceFieldLabel": "Origen de datos",
    "DataSourceSharePointListLabel": "Lista de SharePoint",
    "DataSourceApiEndpointLabel": "Endpoint API",
    "DataSourceStaticConfigLabel": "Configuracion estatica",
    "OneResponsePerUserFieldLabel": "Limitar a una respuesta por usuario",
    "ToggleOnLabel": "Activo",
    "ToggleOffLabel": "Inactivo",
    "ListTitleOrUrlFieldLabel": "Lista de preguntas (titulo o URL)",
    "ResponsesListTitleOrUrlFieldLabel": "Lista de respuestas (titulo o URL)",
    "ApiEndpointUrlFieldLabel": "URL del endpoint",
    "QuestionTextFieldLabel": "Pregunta estatica",
    "OptionsCsvFieldLabel": "Opciones estaticas",
    "WebPartEyebrow": "Participacion ligera",
    "WebPartTitle": "Microencuesta",
    "WebPartSubtitle": "Recoge una senal rapida con una sola pregunta y una unica accion.",
    "LoadingLabel": "Cargando microencuesta",
    "SourceLabel": "Origen",
    "OptionsGroupLabel": "Selecciona una opcion",
    "SubmitAction": "Enviar respuesta",
    "SubmittingAction": "Enviando",
    "RefreshAction": "Actualizar",
    "SuccessStateTitle": "Respuesta registrada",
    "SuccessStateMessage": "Tu respuesta se ha guardado correctamente.",
    "SelectedOptionLabel": "Opcion elegida",
    "ErrorStateTitle": "No se ha podido cargar la microencuesta",
    "ErrorStateMessage": "Revisa la configuracion del origen y vuelve a intentarlo.",
    "EmptyStateTitle": "No hay ninguna pregunta activa",
    "EmptyStateMessage": "Publica una pregunta activa o cambia a un origen con datos.",
    "PartialStateTitle": "Informacion parcial",
    "PartialStateMessage": "La pregunta esta disponible, pero faltan campos opcionales del origen.",
    "InteractionErrorTitle": "No se ha podido completar la accion",
    "SelectionRequiredMessage": "Selecciona una opcion antes de enviar la respuesta.",
    "AlreadyAnsweredMessage": "Ya has respondido esta microencuesta.",
    "QuestionUnavailableMessage": "No hay una pregunta valida disponible para responder.",
    "SubmitErrorMessage": "No se ha podido registrar la respuesta. Intentalo de nuevo.",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la pagina o contacta con el administrador."
  };
});
