define([], function() {
  return {
    "PropertyPaneDescription": "Configure the FAQ catalog shown on the page.",
    "BasicGroupName": "FAQ settings",
    "TitleFieldLabel": "Web part title",
    "DescriptionFieldLabel": "Supporting text",
    "ListTitleFieldLabel": "List name",
    "DefaultCategoryFieldLabel": "Default category",
    "EnableSearchFieldLabel": "Enable search",
    "ToggleOnLabel": "Yes",
    "ToggleOffLabel": "No",
    "MaxItemsFieldLabel": "Maximum number of FAQs",
    "ToggleOnLabel": "Yes",
    "ToggleOffLabel": "No",
    "DefaultTitle": "Smart FAQ",
    "DefaultDescription": "Resolve common questions without leaving the page or duplicating support work.",
    "SearchPlaceholder": "Search by question, answer, or alias",
    "SearchEnabledLabel": "Search enabled",
    "SearchDisabledLabel": "Search disabled",
    "CategoryFilterLabel": "Category",
    "AllCategoriesLabel": "All categories",
    "LoadingMessage": "Loading FAQs",
    "ErrorMessage": "The FAQs could not be loaded.",
    "EmptyMessage": "There are no FAQs available for this configuration or filter.",
    "PartialDataMessage": "Some FAQs are shown with partial metadata. The catalog remains usable.",
    "RetryButtonLabel": "Retry",
    "ExpandButtonLabel": "Expand",
    "CollapseButtonLabel": "Collapse",
    "RelatedLinkLabel": "Open related resource",
    "AliasesLabel": "Aliases",
    "CategoryLabel": "Category",
    "UpdatedAtLabel": "Updated",
    "FeaturedBadgeLabel": "Featured",
    "PartialBadgeLabel": "Partial",
    "ResultsCounterLabel": "FAQs",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
