define([], function() {
  return {
    "PropertyPaneDescription": "Configura el catálogo de preguntas frecuentes que se mostrará en la página.",
    "BasicGroupName": "Configuración de FAQs",
    "TitleFieldLabel": "Título del web part",
    "DescriptionFieldLabel": "Texto de apoyo",
    "ListTitleFieldLabel": "Nombre de la lista",
    "DefaultCategoryFieldLabel": "Categoría por defecto",
    "EnableSearchFieldLabel": "Habilitar búsqueda",
    "ToggleOnLabel": "Sí",
    "ToggleOffLabel": "No",
    "MaxItemsFieldLabel": "Número máximo de FAQs",
    "ToggleOnLabel": "Sí",
    "ToggleOffLabel": "No",
    "DefaultTitle": "FAQ inteligente",
    "DefaultDescription": "Resuelve dudas frecuentes sin salir de la página y sin duplicar soporte.",
    "SearchPlaceholder": "Buscar por pregunta, respuesta o alias",
    "SearchEnabledLabel": "Búsqueda activa",
    "SearchDisabledLabel": "Búsqueda desactivada",
    "CategoryFilterLabel": "Categoría",
    "AllCategoriesLabel": "Todas las categorías",
    "LoadingMessage": "Cargando preguntas frecuentes",
    "ErrorMessage": "No se han podido cargar las FAQs.",
    "EmptyMessage": "No hay FAQs disponibles para esta configuración o filtro.",
    "PartialDataMessage": "Algunas FAQs se muestran con metadatos parciales. El catálogo sigue siendo utilizable.",
    "RetryButtonLabel": "Reintentar",
    "ExpandButtonLabel": "Expandir",
    "CollapseButtonLabel": "Contraer",
    "RelatedLinkLabel": "Abrir recurso relacionado",
    "AliasesLabel": "Alias",
    "CategoryLabel": "Categoría",
    "UpdatedAtLabel": "Actualizada",
    "FeaturedBadgeLabel": "Destacada",
    "PartialBadgeLabel": "Parcial",
    "ResultsCounterLabel": "FAQs",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
