define([], function() {
  return {
    "PropertyPaneDescription": "Configure the corporate glossary displayed on the page.",
    "BasicGroupName": "Glossary settings",
    "TitleFieldLabel": "Web part title",
    "DescriptionFieldLabel": "Supporting text",
    "ListTitleFieldLabel": "Glossary list",
    "DefaultCategoryFieldLabel": "Default category",
    "MaxItemsFieldLabel": "Maximum number of terms",
    "EnableAlphabetNavFieldLabel": "Show alphabetical navigation",
    "ToggleOnLabel": "Yes",
    "ToggleOffLabel": "No",
    "DefaultTitle": "Corporate glossary",
    "DefaultDescription": "Search internal terms, acronyms, and system names without leaving the page.",
    "SearchPlaceholder": "Search a term or alias",
    "SearchAriaLabel": "Search glossary terms",
    "CategoryFilterLabel": "Filter by category",
    "AllCategoriesLabel": "All categories",
    "AllLettersLabel": "All",
    "AlphabetNavLabel": "Alphabet navigation",
    "LoadingMessage": "Loading glossary",
    "ErrorMessage": "The glossary could not be loaded.",
    "EmptyMessage": "There are no terms available for this glossary.",
    "PartialDataMessage": "Some terms have incomplete metadata. The glossary is still usable.",
    "RetryButtonLabel": "Retry",
    "FeaturedBadgeLabel": "Featured",
    "PartialBadgeLabel": "Partial",
    "ResultsCounterLabel": "terms",
    "UpdatedAtLabel": "Updated",
    "OpenReferenceButton": "Open reference",
    "MissingReferenceLabel": "No related link is available for this term.",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  }
});
