define([], function() {
  return {
    "PropertyPaneDescription": "Configura el glosario corporativo que se mostrará en la página.",
    "BasicGroupName": "Configuración del glosario",
    "TitleFieldLabel": "Título del web part",
    "DescriptionFieldLabel": "Texto de apoyo",
    "ListTitleFieldLabel": "Lista de glosario",
    "DefaultCategoryFieldLabel": "Categoría por defecto",
    "MaxItemsFieldLabel": "Número máximo de términos",
    "EnableAlphabetNavFieldLabel": "Mostrar navegación alfabética",
    "ToggleOnLabel": "Sí",
    "ToggleOffLabel": "No",
    "DefaultTitle": "Glosario corporativo",
    "DefaultDescription": "Busca términos internos, siglas y nombres de sistemas sin salir de la página.",
    "SearchPlaceholder": "Buscar término o alias",
    "SearchAriaLabel": "Buscar términos del glosario",
    "CategoryFilterLabel": "Filtrar por categoría",
    "AllCategoriesLabel": "Todas las categorías",
    "AllLettersLabel": "Todas",
    "AlphabetNavLabel": "Navegación alfabética",
    "LoadingMessage": "Cargando glosario",
    "ErrorMessage": "No se ha podido cargar el glosario.",
    "EmptyMessage": "No hay términos disponibles para este glosario.",
    "PartialDataMessage": "Algunos términos tienen metadatos incompletos. El glosario sigue siendo utilizable.",
    "RetryButtonLabel": "Reintentar",
    "FeaturedBadgeLabel": "Destacado",
    "PartialBadgeLabel": "Parcial",
    "ResultsCounterLabel": "términos",
    "UpdatedAtLabel": "Actualizado",
    "OpenReferenceButton": "Abrir referencia",
    "MissingReferenceLabel": "No hay enlace relacionado para este término.",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
