define([], function() {
  return {
    "PropertyPaneDescription": "Configure the source and rendering mode of the intranet portal map.",
    "BasicGroupName": "Portal map settings",
    "DataSourceTypeFieldLabel": "Data source",
    "DataSourceTypeSharePointListOption": "SharePoint list",
    "DataSourceTypeJsonUrlOption": "Same-origin JSON",
    "DataSourceTypeStaticConfigOption": "Static sample",
    "ListTitleOrUrlFieldLabel": "List title or URL",
    "ListTitleOrUrlDescription": "Use a SharePoint list title, a same-origin list URL, or a same-origin JSON URL depending on the selected source.",
    "ViewModeFieldLabel": "Default view",
    "ViewModeTreeOption": "Tree",
    "ViewModeGroupedOption": "Grouped",
    "ViewModeCardsOption": "Cards",
    "MaxDepthFieldLabel": "Maximum hierarchy depth",
    "WebPartTitle": "Portal map",
    "WebPartSubtitle": "Understand the structure of hubs, sites and key areas before you navigate.",
    "SourceLabelPrefix": "Source",
    "ViewSwitcherLabel": "Display mode",
    "StructureSectionTitle": "Portal structure",
    "StateLoadingTitle": "Loading portal structure",
    "StateLoadingMessage": "The map is preparing the portal nodes and relationships.",
    "StateEmptyTitle": "No portal structure available",
    "StateEmptyMessage": "There is no configured structure to show right now.",
    "StateErrorTitle": "Unable to load the portal map",
    "StateErrorMessage": "Review the configured source and try again later.",
    "PartialDataBanner": "The portal map loaded with partial data.",
    "PartialCycleWarning": "A cyclic relationship was detected. The map falls back to a grouped view to stay readable.",
    "PartialOrphanWarning": "Some nodes do not have a valid parent and were promoted to the root level.",
    "PartialNoActionWarning": "Some nodes are informative only because they do not expose a valid navigation URL.",
    "PartialUnknownTypeWarning": "Some nodes do not define a supported type and were grouped as unknown.",
    "PartialDepthWarning": "The configured maximum depth trims deeper levels to keep the map readable.",
    "SourceLabelStaticConfig": "Static sample",
    "SourceLabelJsonUrl": "JSON",
    "SourceLabelSharePointList": "SharePoint list",
    "StatsRootsLabel": "Roots",
    "StatsNodesLabel": "Nodes",
    "TreeAriaLabel": "Portal tree",
    "GroupedAriaLabel": "Portal groups",
    "CardsAriaLabel": "Portal cards",
    "NodeTypeHub": "Hub",
    "NodeTypeSite": "Site",
    "NodeTypeArea": "Area",
    "NodeTypeUtility": "Utility",
    "NodeTypeUnknown": "Unknown",
    "GroupsHubLabel": "Main hubs",
    "GroupsSiteLabel": "Sites",
    "GroupsAreaLabel": "Areas",
    "GroupsUtilityLabel": "Utilities",
    "GroupsUnknownLabel": "Unclassified",
    "NodeBadgeFeatured": "Featured",
    "NodeBadgePartial": "Partial",
    "NodeBadgeOrphan": "Orphan",
    "NodeOpenButton": "Open portal",
    "NodeExpandLabel": "Expand",
    "NodeCollapseLabel": "Collapse",
    "NodeNoLinkMessage": "Informational node with no valid link.",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
