define([], function() {
  return {
    "PropertyPaneDescription": "Configura el origen y el modo de visualización del mapa de portales.",
    "BasicGroupName": "Configuración del mapa",
    "DataSourceTypeFieldLabel": "Origen de datos",
    "DataSourceTypeSharePointListOption": "Lista de SharePoint",
    "DataSourceTypeJsonUrlOption": "JSON same-origin",
    "DataSourceTypeStaticConfigOption": "Muestra estática",
    "ListTitleOrUrlFieldLabel": "Título o URL de la lista",
    "ListTitleOrUrlDescription": "Usa el título de una lista SharePoint, una URL same-origin de lista o una URL JSON same-origin según el origen seleccionado.",
    "ViewModeFieldLabel": "Vista por defecto",
    "ViewModeTreeOption": "Árbol",
    "ViewModeGroupedOption": "Agrupada",
    "ViewModeCardsOption": "Tarjetas",
    "MaxDepthFieldLabel": "Profundidad máxima de jerarquía",
    "WebPartTitle": "Mapa de portales",
    "WebPartSubtitle": "Entiende la estructura de hubs, sites y áreas clave antes de navegar.",
    "SourceLabelPrefix": "Origen",
    "ViewSwitcherLabel": "Modo de visualización",
    "StructureSectionTitle": "Estructura de portales",
    "StateLoadingTitle": "Cargando estructura de portales",
    "StateLoadingMessage": "El mapa está preparando los nodos y sus relaciones.",
    "StateEmptyTitle": "No hay estructura disponible",
    "StateEmptyMessage": "No hay una estructura configurada para mostrar ahora mismo.",
    "StateErrorTitle": "No se ha podido cargar el mapa de portales",
    "StateErrorMessage": "Revisa el origen configurado e inténtalo de nuevo más tarde.",
    "PartialDataBanner": "El mapa se ha cargado con datos parciales.",
    "PartialCycleWarning": "Se ha detectado una relación cíclica. El mapa pasa a vista agrupada para mantener la legibilidad.",
    "PartialOrphanWarning": "Algunos nodos no tienen un padre válido y se han movido al nivel raíz.",
    "PartialNoActionWarning": "Algunos nodos son solo informativos porque no exponen una URL válida de navegación.",
    "PartialUnknownTypeWarning": "Algunos nodos no definen un tipo soportado y se han agrupado como desconocidos.",
    "PartialDepthWarning": "La profundidad máxima configurada recorta niveles para mantener el mapa legible.",
    "SourceLabelStaticConfig": "Muestra estática",
    "SourceLabelJsonUrl": "JSON",
    "SourceLabelSharePointList": "Lista SharePoint",
    "StatsRootsLabel": "Raíces",
    "StatsNodesLabel": "Nodos",
    "TreeAriaLabel": "Árbol de portales",
    "GroupedAriaLabel": "Grupos de portales",
    "CardsAriaLabel": "Tarjetas de portales",
    "NodeTypeHub": "Hub",
    "NodeTypeSite": "Site",
    "NodeTypeArea": "Área",
    "NodeTypeUtility": "Utilidad",
    "NodeTypeUnknown": "Desconocido",
    "GroupsHubLabel": "Hubs principales",
    "GroupsSiteLabel": "Sites",
    "GroupsAreaLabel": "Áreas",
    "GroupsUtilityLabel": "Utilidades",
    "GroupsUnknownLabel": "Sin clasificar",
    "NodeBadgeFeatured": "Destacado",
    "NodeBadgePartial": "Parcial",
    "NodeBadgeOrphan": "Huérfano",
    "NodeOpenButton": "Abrir portal",
    "NodeExpandLabel": "Expandir",
    "NodeCollapseLabel": "Colapsar",
    "NodeNoLinkMessage": "Nodo informativo sin enlace válido.",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
