define([], function() {
  return {
    "PropertyPaneDescription": "Configure the tasks to show",
    "WebPartTitle": "My tasks and pending items",
    "PropertyPaneGeneralGroupName": "General settings",
    "DataSourceFieldLabel": "Data source type",
    "DataSourceSharePointListLabel": "SharePoint list",
    "DataSourceJsonUrlLabel": "JSON URL",
    "DataSourceStaticConfigLabel": "Static configuration",
    "ListTitleOrUrlFieldLabel": "List title or URL",
    "MaxItemsFieldLabel": "Maximum number of tasks",
    "ShowCompletedFieldLabel": "Show completed tasks",
    "ToggleOnLabel": "Yes",
    "ToggleOffLabel": "No",
    "DefaultSortFieldLabel": "Sort by",
    "SortDueDateLabel": "Due date",
    "SortPriorityLabel": "Priority",
    "SortSourceLabel": "Source",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
