define([], function() {
  return {
    "PropertyPaneDescription": "Configura las tareas que se mostrarán",
    "WebPartTitle": "Mis tareas y pendientes",
    "PropertyPaneGeneralGroupName": "Configuración general",
    "DataSourceFieldLabel": "Tipo de origen de datos",
    "DataSourceSharePointListLabel": "Lista de SharePoint",
    "DataSourceJsonUrlLabel": "URL JSON",
    "DataSourceStaticConfigLabel": "Configuración estática",
    "ListTitleOrUrlFieldLabel": "Título o URL de la lista",
    "MaxItemsFieldLabel": "Número máximo de tareas",
    "ShowCompletedFieldLabel": "Mostrar tareas completadas",
    "ToggleOnLabel": "Sí",
    "ToggleOffLabel": "No",
    "DefaultSortFieldLabel": "Ordenar por",
    "SortDueDateLabel": "Fecha de vencimiento",
    "SortPriorityLabel": "Prioridad",
    "SortSourceLabel": "Origen",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
