define([], function() {
  return {
    "PropertyPaneDescription": "Configure the countdown, data source and completion behavior.",
    "SourceGroupName": "Data source",
    "SourceTypeFieldLabel": "Source type",
    "SourceTypeStaticLabel": "Static configuration",
    "SourceTypeSharePointListLabel": "SharePoint list",
    "SourceTypeJsonUrlLabel": "Same-origin JSON",
    "JsonUrlFieldLabel": "JSON URL",
    "ListTitleOrUrlFieldLabel": "List title or URL",
    "EventGroupName": "Event",
    "EventTitleFieldLabel": "Event title",
    "TargetDateFieldLabel": "Target date",
    "SubtitleFieldLabel": "Subtitle",
    "DetailUrlFieldLabel": "Detail URL",
    "MappingGroupName": "Field mapping",
    "TitleFieldLabel": "Title field",
    "TargetDateFieldLabelList": "Target date field",
    "SubtitleFieldLabelList": "Subtitle field",
    "DetailUrlFieldLabelList": "Detail URL field",
    "BehaviorGroupName": "Behavior",
    "ShowCompletedFieldLabel": "Show completed event",
    "RefreshIntervalFieldLabel": "Auto refresh (seconds)",
    "AppLocalEnvironmentSharePoint": "Running locally as a SharePoint web part",
    "AppLocalEnvironmentTeams": "Running locally as a Microsoft Teams app",
    "AppLocalEnvironmentOffice": "Running locally in office.com",
    "AppLocalEnvironmentOutlook": "Running locally in Outlook",
    "AppSharePointEnvironment": "Running on a SharePoint page",
    "AppTeamsTabEnvironment": "Running in Microsoft Teams",
    "AppOfficeEnvironment": "Running in office.com",
    "AppOutlookEnvironment": "Running in Outlook",
    "UnknownEnvironment": "Running in an unknown environment",
    "DefaultEventTitle": "Event countdown",
    "SectionAriaLabel": "Event countdown",
    "SourceFooterLabel": "Source",
    "OpenDetailButtonLabel": "Open details",
    "UnsafeLinkMessage": "The configured link is not safe or could not be validated.",
    "ErrorStateTitle": "The countdown could not be calculated",
    "ErrorStateMessage": "Review the source configuration or target date.",
    "EmptyStateTitle": "There is no active event",
    "PartialWarningMessage": "Part of the information is incomplete, but the countdown is still usable.",
    "LiveBadgeLabel": "Event in progress",
    "CompletedBadgeLabel": "Event completed",
    "DaysLabel": "days",
    "HoursLabel": "hours",
    "MinutesLabel": "minutes",
    "CountdownPhaseLabel": "Countdown",
    "LivePhaseLabel": "Live",
    "CompletedPhaseLabel": "Completed",
    "UnknownPhaseLabel": "Unknown",
    "EmptyPhaseLabel": "No event",
    "ErrorPhaseLabel": "Error",
    "EmptyEventMessage": "There is no configured event.",
    "InvalidTargetDateMessage": "The target date could not be interpreted.",
    "CompletedHiddenMessage": "The event has already finished and is hidden by configuration.",
    "LoadingSourceLabel": "Loading",
    "LoadingSupportingText": "Loading the countdown.",
    "StaticSourceLabel": "Static configuration",
    "SharePointSourceLabel": "SharePoint list",
    "JsonSourceLabel": "JSON URL",
    "EmptySourceNote": "The source returned no items.",
    "MultipleRecordsNote": "The source returned several items; the first compatible one will be used.",
    "CountdownSupportingPrefix": "There are",
    "CountdownSupportingConnector": "left for",
    "LiveSupportingPrefix": "The event",
    "LiveSupportingConnector": "is live since",
    "CompletedSupportingPrefix": "The event",
    "CompletedSupportingConnector": "finished on",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
