define([], function() {
  return {
    "PropertyPaneDescription": "Configura la cuenta atrás, la fuente de datos y el comportamiento de cierre.",
    "SourceGroupName": "Origen de datos",
    "SourceTypeFieldLabel": "Tipo de origen",
    "SourceTypeStaticLabel": "Configuración estática",
    "SourceTypeSharePointListLabel": "Lista de SharePoint",
    "SourceTypeJsonUrlLabel": "JSON same-origin",
    "JsonUrlFieldLabel": "URL JSON",
    "ListTitleOrUrlFieldLabel": "Título o URL de lista",
    "EventGroupName": "Evento",
    "EventTitleFieldLabel": "Título del evento",
    "TargetDateFieldLabel": "Fecha objetivo",
    "SubtitleFieldLabel": "Subtítulo",
    "DetailUrlFieldLabel": "URL de detalle",
    "MappingGroupName": "Mapeo de campos",
    "TitleFieldLabel": "Campo de título",
    "TargetDateFieldLabelList": "Campo de fecha objetivo",
    "SubtitleFieldLabelList": "Campo de subtítulo",
    "DetailUrlFieldLabelList": "Campo de URL de detalle",
    "BehaviorGroupName": "Comportamiento",
    "ShowCompletedFieldLabel": "Mostrar evento completado",
    "RefreshIntervalFieldLabel": "Refresco automático (segundos)",
    "AppLocalEnvironmentSharePoint": "Ejecutándose localmente como web part de SharePoint",
    "AppLocalEnvironmentTeams": "Ejecutándose localmente como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "Ejecutándose localmente en office.com",
    "AppLocalEnvironmentOutlook": "Ejecutándose localmente en Outlook",
    "AppSharePointEnvironment": "Ejecutándose en una página de SharePoint",
    "AppTeamsTabEnvironment": "Ejecutándose en Microsoft Teams",
    "AppOfficeEnvironment": "Ejecutándose en office.com",
    "AppOutlookEnvironment": "Ejecutándose en Outlook",
    "UnknownEnvironment": "Ejecutándose en un entorno desconocido"
    ErrorBoundaryTitle: "Something went wrong",
    ErrorBoundaryMessage: "This web part encountered an unexpected error. Please reload the page or contact your administrator.",
  };
});
