define([], function() {
  return {
    "PropertyPaneDescription": "Configura la cuenta atras, la fuente de datos y el comportamiento de cierre.",
    "SourceGroupName": "Origen de datos",
    "SourceTypeFieldLabel": "Tipo de origen",
    "SourceTypeStaticLabel": "Configuracion estatica",
    "SourceTypeSharePointListLabel": "Lista de SharePoint",
    "SourceTypeJsonUrlLabel": "JSON same-origin",
    "JsonUrlFieldLabel": "URL JSON",
    "ListTitleOrUrlFieldLabel": "Titulo o URL de lista",
    "EventGroupName": "Evento",
    "EventTitleFieldLabel": "Titulo del evento",
    "TargetDateFieldLabel": "Fecha objetivo",
    "SubtitleFieldLabel": "Subtitulo",
    "DetailUrlFieldLabel": "URL de detalle",
    "MappingGroupName": "Mapeo de campos",
    "TitleFieldLabel": "Campo de titulo",
    "TargetDateFieldLabelList": "Campo de fecha objetivo",
    "SubtitleFieldLabelList": "Campo de subtitulo",
    "DetailUrlFieldLabelList": "Campo de URL de detalle",
    "BehaviorGroupName": "Comportamiento",
    "ShowCompletedFieldLabel": "Mostrar evento completado",
    "RefreshIntervalFieldLabel": "Refresco automatico (segundos)",
    "AppLocalEnvironmentSharePoint": "Ejecutandose localmente como web part de SharePoint",
    "AppLocalEnvironmentTeams": "Ejecutandose localmente como aplicacion de Microsoft Teams",
    "AppLocalEnvironmentOffice": "Ejecutandose localmente en office.com",
    "AppLocalEnvironmentOutlook": "Ejecutandose localmente en Outlook",
    "AppSharePointEnvironment": "Ejecutandose en una pagina de SharePoint",
    "AppTeamsTabEnvironment": "Ejecutandose en Microsoft Teams",
    "AppOfficeEnvironment": "Ejecutandose en office.com",
    "AppOutlookEnvironment": "Ejecutandose en Outlook",
    "UnknownEnvironment": "Ejecutandose en un entorno desconocido",
    "DefaultEventTitle": "Cuenta atras a eventos",
    "SectionAriaLabel": "Cuenta atras a eventos",
    "SourceFooterLabel": "Origen",
    "OpenDetailButtonLabel": "Abrir detalle",
    "UnsafeLinkMessage": "El enlace configurado no es seguro o no se pudo validar.",
    "ErrorStateTitle": "No se ha podido calcular la cuenta atras",
    "ErrorStateMessage": "Revisa la configuracion de la fuente o la fecha objetivo.",
    "EmptyStateTitle": "No hay evento activo",
    "PartialWarningMessage": "Parte de la informacion no esta completa, pero la cuenta atras sigue siendo utilizable.",
    "LiveBadgeLabel": "El evento esta en curso",
    "CompletedBadgeLabel": "Evento completado",
    "DaysLabel": "dias",
    "HoursLabel": "horas",
    "MinutesLabel": "minutos",
    "CountdownPhaseLabel": "Cuenta atras",
    "LivePhaseLabel": "En curso",
    "CompletedPhaseLabel": "Completado",
    "UnknownPhaseLabel": "Sin estado",
    "EmptyPhaseLabel": "Sin evento",
    "ErrorPhaseLabel": "Error",
    "EmptyEventMessage": "No hay evento configurado.",
    "InvalidTargetDateMessage": "No se ha podido interpretar la fecha objetivo.",
    "CompletedHiddenMessage": "El evento ya ha finalizado y esta oculto por configuracion.",
    "LoadingSourceLabel": "Cargando",
    "LoadingSupportingText": "Cargando la cuenta atras.",
    "StaticSourceLabel": "Configuracion estatica",
    "SharePointSourceLabel": "Lista de SharePoint",
    "JsonSourceLabel": "JSON URL",
    "EmptySourceNote": "El origen no devolvio elementos.",
    "MultipleRecordsNote": "El origen devolvio varios elementos; se usara el primero compatible.",
    "CountdownSupportingPrefix": "Faltan",
    "CountdownSupportingConnector": "para",
    "LiveSupportingPrefix": "El evento",
    "LiveSupportingConnector": "esta en curso desde",
    "CompletedSupportingPrefix": "El evento",
    "CompletedSupportingConnector": "finalizo el",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la pagina o contacta con el administrador."
  };
});
