declare interface IEventCountdownWebPartStrings {
  PropertyPaneDescription: string;
  SourceGroupName: string;
  SourceTypeFieldLabel: string;
  SourceTypeStaticLabel: string;
  SourceTypeSharePointListLabel: string;
  SourceTypeJsonUrlLabel: string;
  JsonUrlFieldLabel: string;
  ListTitleOrUrlFieldLabel: string;
  EventGroupName: string;
  EventTitleFieldLabel: string;
  TargetDateFieldLabel: string;
  SubtitleFieldLabel: string;
  DetailUrlFieldLabel: string;
  MappingGroupName: string;
  TitleFieldLabel: string;
  TargetDateFieldLabelList: string;
  SubtitleFieldLabelList: string;
  DetailUrlFieldLabelList: string;
  BehaviorGroupName: string;
  ShowCompletedFieldLabel: string;
  RefreshIntervalFieldLabel: string;
  AppLocalEnvironmentSharePoint: string;
  AppLocalEnvironmentTeams: string;
  AppLocalEnvironmentOffice: string;
  AppLocalEnvironmentOutlook: string;
  AppSharePointEnvironment: string;
  AppTeamsTabEnvironment: string;
  AppOfficeEnvironment: string;
  AppOutlookEnvironment: string;
  UnknownEnvironment: string;
  DefaultEventTitle: string;
  SectionAriaLabel: string;
  SourceFooterLabel: string;
  OpenDetailButtonLabel: string;
  UnsafeLinkMessage: string;
  ErrorStateTitle: string;
  ErrorStateMessage: string;
  EmptyStateTitle: string;
  PartialWarningMessage: string;
  LiveBadgeLabel: string;
  CompletedBadgeLabel: string;
  DaysLabel: string;
  HoursLabel: string;
  MinutesLabel: string;
  CountdownPhaseLabel: string;
  LivePhaseLabel: string;
  CompletedPhaseLabel: string;
  UnknownPhaseLabel: string;
  EmptyPhaseLabel: string;
  ErrorPhaseLabel: string;
  EmptyEventMessage: string;
  InvalidTargetDateMessage: string;
  CompletedHiddenMessage: string;
  LoadingSourceLabel: string;
  LoadingSupportingText: string;
  StaticSourceLabel: string;
  SharePointSourceLabel: string;
  JsonSourceLabel: string;
  EmptySourceNote: string;
  MultipleRecordsNote: string;
  CountdownSupportingPrefix: string;
  CountdownSupportingConnector: string;
  LiveSupportingPrefix: string;
  LiveSupportingConnector: string;
  CompletedSupportingPrefix: string;
  CompletedSupportingConnector: string;
  ErrorBoundaryTitle: string;
  ErrorBoundaryMessage: string;
}

declare module 'EventCountdownWebPartStrings' {
  const strings: IEventCountdownWebPartStrings;
  export = strings;
}
