define([], function() {
  return {
    "Title": "Mini organigrama",
    "PropertyPaneDescription": "Configure the data sources and behavior for the mini organigram.",
    "BasicGroupName": "Basic settings",
    "DataSourcesGroupName": "Data sources",
    "TitleFieldLabel": "Title",
    "DescriptionFieldLabel": "Description",
    "DataSourceTypesFieldLabel": "Data source types",
    "DataSourceTypesFieldDescription": "Comma-separated values: Directory, SharePointList, JsonUrl, StaticConfig.",
    "DirectoryEndpointFieldLabel": "Directory endpoint",
    "DirectoryEndpointFieldDescription": "Same-origin JSON endpoint that returns manager and reports records.",
    "ListTitleOrUrlFieldLabel": "List title or URL",
    "ListTitleOrUrlFieldDescription": "SharePoint list title or a same-origin list URL. AllItems.aspx paths are normalized automatically.",
    "JsonUrlFieldLabel": "JSON URL",
    "JsonUrlFieldDescription": "Same-origin JSON endpoint with people items.",
    "StaticConfigJsonFieldLabel": "Static config JSON",
    "StaticConfigJsonFieldDescription": "Inline JSON payload with items or { items: [...] }.",
    "RootPersonIdFieldLabel": "Root person ID",
    "RootPersonIdFieldDescription": "Optional person ID to force the top node.",
    "ViewModeFieldLabel": "View mode",
    "ViewModeManagerWithReportsLabel": "Manager with reports",
    "ViewModeChainLabel": "Reporting chain",
    "ViewModeSmallTreeLabel": "Small tree",
    "MaxDepthFieldLabel": "Max depth",
    "MaxDepthFieldDescription": "Allowed range: 1 to 4.",
    "SearchLabel": "Search people",
    "SearchPlaceholder": "Search by name, title, department or email",
    "FiltersLabel": "Refine view",
    "ResultsCountLabel": "Visible people",
    "ReloadLabel": "Reload",
    "OpenProfileLabel": "Open profile",
    "RootBadgeLabel": "Root",
    "PartialBadgeLabel": "Partial",
    "LoadingTitle": "Loading mini organigram",
    "LoadingMessage": "Retrieving organizational data.",
    "EmptyTitle": "No structure available",
    "EmptyMessage": "No organizational structure is available for this configuration.",
    "NoMatchesTitle": "No matches",
    "NoMatchesMessage": "Try a different search term or view mode.",
    "PartialDataTitle": "Partial data",
    "PartialDataMessage": "Some relationships or profile data are missing, but the view can still be used.",
    "ErrorTitle": "Unable to load the mini organigram.",
    "ErrorMessage": "Check the configured sources and try again.",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator.",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  };
});

