define([], function() {
  return {
    "Title": "Mini organigrama",
    "PropertyPaneDescription": "Configura las fuentes de datos y el comportamiento del mini organigrama.",
    "BasicGroupName": "Configuración básica",
    "DataSourcesGroupName": "Fuentes de datos",
    "TitleFieldLabel": "Título",
    "DescriptionFieldLabel": "Descripción",
    "DataSourceTypesFieldLabel": "Tipos de fuente",
    "DataSourceTypesFieldDescription": "Valores separados por coma: Directory, SharePointList, JsonUrl, StaticConfig.",
    "DirectoryEndpointFieldLabel": "Endpoint de directorio",
    "DirectoryEndpointFieldDescription": "Endpoint JSON same-origin que devuelve relaciones de manager y equipo.",
    "ListTitleOrUrlFieldLabel": "Título o URL de la lista",
    "ListTitleOrUrlFieldDescription": "Título de la lista de SharePoint o URL same-origin de lista. Las rutas AllItems.aspx se normalizan automáticamente.",
    "JsonUrlFieldLabel": "URL JSON",
    "JsonUrlFieldDescription": "Endpoint JSON same-origin con personas.",
    "StaticConfigJsonFieldLabel": "JSON estático",
    "StaticConfigJsonFieldDescription": "Carga JSON incrustado con items o con { items: [...] }.",
    "RootPersonIdFieldLabel": "ID de la persona raíz",
    "RootPersonIdFieldDescription": "ID opcional para forzar el nodo superior.",
    "ViewModeFieldLabel": "Modo de vista",
    "ViewModeManagerWithReportsLabel": "Manager con reportes",
    "ViewModeChainLabel": "Cadena jerárquica",
    "ViewModeSmallTreeLabel": "Árbol pequeño",
    "MaxDepthFieldLabel": "Profundidad máxima",
    "MaxDepthFieldDescription": "Rango permitido: 1 a 4.",
    "SearchLabel": "Buscar personas",
    "SearchPlaceholder": "Buscar por nombre, cargo, departamento o email",
    "FiltersLabel": "Ajustar vista",
    "ResultsCountLabel": "Personas visibles",
    "ReloadLabel": "Recargar",
    "OpenProfileLabel": "Abrir perfil",
    "RootBadgeLabel": "Raíz",
    "PartialBadgeLabel": "Parcial",
    "LoadingTitle": "Cargando mini organigrama",
    "LoadingMessage": "Recuperando los datos organizativos.",
    "EmptyTitle": "No hay estructura disponible",
    "EmptyMessage": "No hay una estructura organizativa disponible para esta configuración.",
    "NoMatchesTitle": "Sin coincidencias",
    "NoMatchesMessage": "Prueba con otro término de búsqueda o modo de vista.",
    "PartialDataTitle": "Datos parciales",
    "PartialDataMessage": "Faltan algunas relaciones o datos de perfil, pero la vista puede seguir usándose.",
    "ErrorTitle": "No se ha podido cargar el mini organigrama.",
    "ErrorMessage": "Revisa las fuentes configuradas y vuelve a intentarlo.",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador.",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido"
  };
});

