define([], function() {
  return {
    "PropertyPaneDescription": "Configure the corporate templates catalog shown on the page.",
    "BasicGroupName": "Catalog configuration",
    "TitleFieldLabel": "Web part title",
    "DescriptionFieldLabel": "Supporting text",
    "SourceKindFieldLabel": "Source type",
    "SourceKindLibraryLabel": "Document library",
    "SourceKindListLabel": "Catalog list",
    "ListTitleFieldLabel": "List or library name",
    "DefaultCategoryFieldLabel": "Default category",
    "MaxItemsFieldLabel": "Maximum number of templates",
    "DefaultTitle": "Templates library",
    "DefaultDescription": "Access official templates without relying on scattered links or outdated versions.",
    "SearchPlaceholder": "Search by title, category, or type",
    "CategoryFilterLabel": "Category",
    "TypeFilterLabel": "Type",
    "AllCategoriesLabel": "All categories",
    "AllTypesLabel": "All types",
    "LoadingMessage": "Loading templates",
    "ErrorMessage": "The official templates could not be loaded.",
    "EmptyMessage": "There are no templates available for this configuration or filter.",
    "PartialDataMessage": "Some templates are shown with partial metadata. The catalog remains usable.",
    "RetryButtonLabel": "Retry",
    "OpenTemplateButton": "Open template",
    "DownloadTemplateButton": "Download",
    "MissingActionLabel": "This template does not have an available action.",
    "FeaturedBadgeLabel": "Featured",
    "PartialBadgeLabel": "Partial",
    "UpdatedAtLabel": "Updated",
    "ResultsCounterLabel": "templates",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
