define([], function() {
  return {
    "PropertyPaneDescription": "Configura el catálogo de plantillas corporativas disponible en la página.",
    "BasicGroupName": "Configuración del catálogo",
    "TitleFieldLabel": "Título del web part",
    "DescriptionFieldLabel": "Texto de apoyo",
    "SourceKindFieldLabel": "Tipo de origen",
    "SourceKindLibraryLabel": "Biblioteca de documentos",
    "SourceKindListLabel": "Lista de catálogo",
    "ListTitleFieldLabel": "Nombre de la lista o biblioteca",
    "DefaultCategoryFieldLabel": "Categoría por defecto",
    "MaxItemsFieldLabel": "Número máximo de plantillas",
    "DefaultTitle": "Biblioteca de plantillas",
    "DefaultDescription": "Accede a las plantillas oficiales sin depender de enlaces dispersos ni versiones antiguas.",
    "SearchPlaceholder": "Buscar por título, categoría o tipo",
    "CategoryFilterLabel": "Categoría",
    "TypeFilterLabel": "Tipo",
    "AllCategoriesLabel": "Todas las categorías",
    "AllTypesLabel": "Todos los tipos",
    "LoadingMessage": "Cargando plantillas",
    "ErrorMessage": "No se han podido cargar las plantillas oficiales.",
    "EmptyMessage": "No hay plantillas disponibles para esta configuración o filtro.",
    "PartialDataMessage": "Algunas plantillas se muestran con metadatos parciales. El catálogo sigue siendo usable.",
    "RetryButtonLabel": "Reintentar",
    "OpenTemplateButton": "Abrir plantilla",
    "DownloadTemplateButton": "Descargar",
    "MissingActionLabel": "Esta plantilla no tiene acción disponible.",
    "FeaturedBadgeLabel": "Destacada",
    "PartialBadgeLabel": "Parcial",
    "UpdatedAtLabel": "Actualizada",
    "ResultsCounterLabel": "plantillas",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
