define([], function() {
  return {
    "PropertyPaneDescription": "Configure the guides catalog and its default filter.",
    "BasicGroupName": "Settings",
    "TitleFieldLabel": "Title",
    "DescriptionFieldLabel": "Description",
    "DataSourceTypeFieldLabel": "Data source",
    "SharePointListOptionLabel": "SharePoint list",
    "JsonUrlOptionLabel": "JSON URL",
    "StaticConfigOptionLabel": "Built-in sample catalog",
    "ListTitleOrUrlFieldLabel": "List title or URL",
    "DefaultCategoryFieldLabel": "Default category",
    "MaxItemsFieldLabel": "Maximum guides",
    "VisibleGuidesLabel": "Visible guides",
    "CategoryFilterLabel": "Filter by category",
    "FilterAllLabel": "All",
    "LoadingMessage": "Loading guides...",
    "EmptyMessage": "There are no guides available right now.",
    "EmptyHint": "Adjust the configured source or switch to the sample catalog while the list is being provisioned.",
    "PartialDataMessage": "Some guides have incomplete data. They are still shown with safe fallbacks.",
    "ErrorMessage": "We couldn't load the guides.",
    "ExpandLabel": "Show steps",
    "CollapseLabel": "Hide steps",
    "StepsHeading": "Steps",
    "RelatedLinkLabel": "Open related resource",
    "FeaturedBadgeLabel": "Featured",
    "PartialBadgeLabel": "Partial data",
    "AppLocalEnvironmentSharePoint": "The app is running in your local environment as a SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running in your local environment as a Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running in your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running in your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on a SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "ErrorBoundaryTitle": "Something went wrong",
    "ErrorBoundaryMessage": "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  }
});
