define([], function() {
  return {
    "PropertyPaneDescription": "Configura el catálogo de guías y su filtro por defecto.",
    "BasicGroupName": "Configuración",
    "TitleFieldLabel": "Título",
    "DescriptionFieldLabel": "Descripción",
    "DataSourceTypeFieldLabel": "Origen de datos",
    "SharePointListOptionLabel": "Lista de SharePoint",
    "JsonUrlOptionLabel": "URL JSON",
    "StaticConfigOptionLabel": "Catálogo de ejemplo integrado",
    "ListTitleOrUrlFieldLabel": "Título o URL de la lista",
    "DefaultCategoryFieldLabel": "Categoría por defecto",
    "MaxItemsFieldLabel": "Guías máximas",
    "VisibleGuidesLabel": "Guías visibles",
    "CategoryFilterLabel": "Filtrar por categoría",
    "FilterAllLabel": "Todas",
    "LoadingMessage": "Cargando guías...",
    "EmptyMessage": "No hay guías disponibles ahora mismo.",
    "EmptyHint": "Ajusta el origen configurado o usa el catálogo de ejemplo mientras se provisiona la lista.",
    "PartialDataMessage": "Algunas guías tienen datos incompletos. Se muestran igualmente con fallback seguro.",
    "ErrorMessage": "No se han podido cargar las guías.",
    "ExpandLabel": "Ver pasos",
    "CollapseLabel": "Ocultar pasos",
    "StepsHeading": "Pasos",
    "RelatedLinkLabel": "Abrir recurso relacionado",
    "FeaturedBadgeLabel": "Destacada",
    "PartialBadgeLabel": "Datos parciales",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  }
});
