define([], function() {
  return {
    "PropertyPaneDescription": "Configuración de Próximos hitos",
    "BasicGroupName": "Contenido",
    "TitleFieldLabel": "Título",
    "DescriptionFieldLabel": "Descripción",
    "ListTitleFieldLabel": "Lista de hitos",
    "MaxItemsFieldLabel": "Número máximo de hitos",
    "ViewModeFieldLabel": "Modo de visualización",
    "ViewModeTimelineLabel": "Timeline",
    "ViewModeListLabel": "Lista",
    "ViewModePillLabel": "Vista:",
    "DefaultTitle": "Próximos hitos",
    "DefaultDescription": "Fechas y entregables que conviene tener visibles en la semana.",
    "LoadingMessage": "Cargando hitos...",
    "ErrorMessage": "No se han podido cargar los hitos.",
    "EmptyMessage": "No hay hitos próximos configurados.",
    "PartialDataMessage": "Se han cargado hitos con datos parciales. Revisa fechas, tipos o enlaces.",
    "RetryButtonLabel": "Reintentar",
    "OpenMilestoneButton": "Abrir detalle",
    "InformationalLabel": "Hito informativo sin detalle",
    "SoonBadgeLabel": "Próximo",
    "PartialBadgeLabel": "Parcial",
    "ResultsCounterLabel": "hitos",
    "DateMissingLabel": "Fecha pendiente",
    "TypeMissingLabel": "Fase no definida",
    "TimelineAriaLabel": "Timeline de próximos hitos",
    "ListAriaLabel": "Lista de próximos hitos",
    "AppLocalEnvironmentSharePoint": "La aplicación se está ejecutando en tu entorno local como web part de SharePoint",
    "AppLocalEnvironmentTeams": "La aplicación se está ejecutando en tu entorno local como aplicación de Microsoft Teams",
    "AppLocalEnvironmentOffice": "La aplicación se está ejecutando en tu entorno local en office.com",
    "AppLocalEnvironmentOutlook": "La aplicación se está ejecutando en tu entorno local en Outlook",
    "AppSharePointEnvironment": "La aplicación se está ejecutando en una página de SharePoint",
    "AppTeamsTabEnvironment": "La aplicación se está ejecutando en Microsoft Teams",
    "AppOfficeEnvironment": "La aplicación se está ejecutando en office.com",
    "AppOutlookEnvironment": "La aplicación se está ejecutando en Outlook",
    "UnknownEnvironment": "La aplicación se está ejecutando en un entorno desconocido",
    "ErrorBoundaryTitle": "Se ha producido un error inesperado",
    "ErrorBoundaryMessage": "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
