define([], function() {
  return {
    PropertyPaneDescription: "Configure multi-site scanning. Saving is optional and only supported in a list that belongs to the current site.",
    BasicGroupName: "Scan configuration",
    ReportListUrlFieldLabel: "Optional local report list URL",
    ReportListUrlFieldDescription: "It must belong to the current site. If you leave it empty, you can still scan and download the full CSV without saving anything.",
    BatchSizeFieldLabel: "Batch size (sites per flush)",
    MaxRequestsPerSecondFieldLabel: "Max requests per second",
    ScopeFieldLabel: "Scan scope",
    ScopeAllOptionText: "All accessible site collections",
    ScopeManualOptionText: "Manual URLs",
    ManualSiteUrlsFieldLabel: "Manual site URLs (one per line)",
    SaveOptionalInfoMessage: "Saving to SharePoint is optional. If you provide a list, it must belong to this current site. You can always download the full result as CSV without persisting anything.",
    DashboardTabLabel: "Dashboard",
    ScanTabLabel: "Scan",
    DashboardTitle: "Storage dashboard",
    SitesLabel: "sites",
    DashboardEmptyMessage: "No reports are available yet. Start a scan from the scan tab.",
    DashboardHintMessage: "\"Unavailable\" means SharePoint did not return that value or the site did not allow access to that resource. Expand the row to inspect the detail.",
    DownloadCsvButtonLabel: "Download CSV",
    ExpandRowAriaLabel: "Expand detail",
    CollapseRowAriaLabel: "Collapse detail",
    SiteColumnLabel: "Site",
    SiteUrlLabel: "Site URL",
    LibrariesColumnLabel: "Libraries",
    ItemsColumnLabel: "Items",
    RecycleBinColumnLabel: "Recycle bin",
    RecycleBinSizeColumnLabel: "Recycle bin size",
    StorageColumnLabel: "Storage",
    FlagsColumnLabel: "Alerts",
    ScanDateColumnLabel: "Last scan",
    NoAlertsLabel: "No alerts",
    HealthyLabel: "Healthy",
    WarningLabel: "Warning",
    CriticalLabel: "Critical",
    UnknownLabel: "Unknown",
    UnavailableLabel: "Unavailable",
    UnavailableHintMessage: "SharePoint did not return this value during the scan.",
    RecycleBinUnavailableLabel: "No access",
    HealthLabel: "Health status",
    ErrorLabel: "Error",
    LibraryInventoryLabel: "Library and item inventory",
    NoLibrariesLabel: "This site did not return libraries during the scan.",
    LibraryNameColumnLabel: "Library",
    LibraryLastModifiedColumnLabel: "Last modified",
    LoadingItemsLabel: "Loading library items...",
    NoItemsLabel: "No items were returned for this library.",
    ItemNameColumnLabel: "Item",
    ItemTypeColumnLabel: "Type",
    ItemSizeColumnLabel: "Size",
    ItemModifiedColumnLabel: "Modified",
    ItemModifiedByColumnLabel: "Modified by",
    FolderItemTypeLabel: "Folder",
    FileItemTypeLabel: "File",
    NotApplicableLabel: "Not applicable",
    ErrorBoundaryTitle: "Something went wrong",
    ErrorBoundaryMessage: "This web part encountered an unexpected error. Please reload the page or contact your administrator."
  };
});
