define([], function() {
  return {
    PropertyPaneDescription: "Configura el escaneo multi-sitio. El guardado es opcional y solo se admite en una lista del sitio actual.",
    BasicGroupName: "Configuración del escaneo",
    ReportListUrlFieldLabel: "URL opcional de la lista local de informes",
    ReportListUrlFieldDescription: "Debe pertenecer al sitio actual. Si la dejas vacía, podrás escanear y descargar CSV sin guardar nada.",
    BatchSizeFieldLabel: "Tamaño de lote (sites por flush)",
    MaxRequestsPerSecondFieldLabel: "Máximo de peticiones por segundo",
    ScopeFieldLabel: "Alcance del escaneo",
    ScopeAllOptionText: "Todas las colecciones de sitios accesibles",
    ScopeManualOptionText: "URLs manuales",
    ManualSiteUrlsFieldLabel: "URLs manuales (una por línea)",
    SaveOptionalInfoMessage: "El guardado en SharePoint es opcional. Si indicas una lista, debe pertenecer a este mismo sitio. Siempre podrás descargar el resultado completo en CSV sin persistir nada.",
    DashboardTabLabel: "Dashboard",
    ScanTabLabel: "Escaneo",
    DashboardTitle: "Dashboard de almacenamiento",
    SitesLabel: "sitios",
    DashboardEmptyMessage: "No hay informes disponibles. Inicia un escaneo desde la pestaña de escaneo.",
    DashboardHintMessage: "\"No disponible\" indica que SharePoint no devolvió ese dato o que el sitio no permitió acceder a ese recurso. Abre la fila para ver el detalle.",
    DownloadCsvButtonLabel: "Descargar CSV",
    ExpandRowAriaLabel: "Expandir detalle",
    CollapseRowAriaLabel: "Contraer detalle",
    SiteColumnLabel: "Sitio",
    SiteUrlLabel: "URL del sitio",
    LibrariesColumnLabel: "Bibliotecas",
    ItemsColumnLabel: "Items",
    RecycleBinColumnLabel: "Papelera",
    RecycleBinSizeColumnLabel: "Tamaño papelera",
    StorageColumnLabel: "Almacenamiento",
    FlagsColumnLabel: "Alertas",
    ScanDateColumnLabel: "Último escaneo",
    NoAlertsLabel: "Sin alertas",
    HealthyLabel: "Saludable",
    WarningLabel: "Advertencia",
    CriticalLabel: "Crítico",
    UnknownLabel: "Desconocido",
    UnavailableLabel: "No disponible",
    UnavailableHintMessage: "SharePoint no devolvió el dato durante el escaneo.",
    RecycleBinUnavailableLabel: "Sin acceso",
    HealthLabel: "Estado de salud",
    ErrorLabel: "Error",
    LibraryInventoryLabel: "Inventario de bibliotecas e items",
    NoLibrariesLabel: "Este sitio no devolvió bibliotecas durante el escaneo.",
    LibraryNameColumnLabel: "Biblioteca",
    LibraryLastModifiedColumnLabel: "Última modificación",
    LoadingItemsLabel: "Cargando items de la biblioteca...",
    NoItemsLabel: "No se han devuelto items para esta biblioteca.",
    ItemNameColumnLabel: "Item",
    ItemTypeColumnLabel: "Tipo",
    ItemSizeColumnLabel: "Tamaño",
    ItemModifiedColumnLabel: "Modificado",
    ItemModifiedByColumnLabel: "Modificado por",
    FolderItemTypeLabel: "Carpeta",
    FileItemTypeLabel: "Archivo",
    NotApplicableLabel: "No aplica",
    ErrorBoundaryTitle: "Se ha producido un error inesperado",
    ErrorBoundaryMessage: "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
