declare interface ISiteStorageDiagnosticsWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  ReportListUrlFieldLabel: string;
  ReportListUrlFieldDescription: string;
  BatchSizeFieldLabel: string;
  MaxRequestsPerSecondFieldLabel: string;
  ScopeFieldLabel: string;
  ScopeAllOptionText: string;
  ScopeManualOptionText: string;
  ManualSiteUrlsFieldLabel: string;
  SaveOptionalInfoMessage: string;
  DashboardTabLabel: string;
  ScanTabLabel: string;
  DashboardTitle: string;
  SitesLabel: string;
  DashboardEmptyMessage: string;
  DashboardHintMessage: string;
  DownloadCsvButtonLabel: string;
  ExpandRowAriaLabel: string;
  CollapseRowAriaLabel: string;
  SiteColumnLabel: string;
  SiteUrlLabel: string;
  LibrariesColumnLabel: string;
  ItemsColumnLabel: string;
  RecycleBinColumnLabel: string;
  RecycleBinSizeColumnLabel: string;
  StorageColumnLabel: string;
  FlagsColumnLabel: string;
  ScanDateColumnLabel: string;
  NoAlertsLabel: string;
  HealthyLabel: string;
  WarningLabel: string;
  CriticalLabel: string;
  UnknownLabel: string;
  UnavailableLabel: string;
  UnavailableHintMessage: string;
  RecycleBinUnavailableLabel: string;
  HealthLabel: string;
  ErrorLabel: string;
  LibraryInventoryLabel: string;
  NoLibrariesLabel: string;
  LibraryNameColumnLabel: string;
  LibraryLastModifiedColumnLabel: string;
  LoadingItemsLabel: string;
  NoItemsLabel: string;
  ItemNameColumnLabel: string;
  ItemTypeColumnLabel: string;
  ItemSizeColumnLabel: string;
  ItemModifiedColumnLabel: string;
  ItemModifiedByColumnLabel: string;
  FolderItemTypeLabel: string;
  FileItemTypeLabel: string;
  NotApplicableLabel: string;
  ErrorBoundaryTitle: string;
  ErrorBoundaryMessage: string;
}

declare module 'SiteStorageDiagnosticsWebPartStrings' {
  const strings: ISiteStorageDiagnosticsWebPartStrings;
  export = strings;
}
