define([], function () {
  return {
    PropertyPaneDescription: 'Configures audience-segmented quick links',
    BasicGroupName: 'Content and audience',
    TitleFieldLabel: 'Web part title',
    DescriptionFieldLabel: 'Brief description',
    DataSourceTypeFieldLabel: 'Data source',
    SharePointListLabel: 'SharePoint list',
    JsonUrlLabel: 'JSON URL (same origin)',
    StaticConfigLabel: 'Internal catalog',
    ListTitleOrUrlFieldLabel: 'List name or same-origin JSON URL',
    AudienceModeFieldLabel: 'Audience mode',
    GroupLabel: 'Group',
    DepartmentLabel: 'Department',
    CountryLabel: 'Country',
    RoleLabel: 'Role',
    HybridLabel: 'Hybrid',
    DefaultCategoryFieldLabel: 'Default category',
    MaxItemsFieldLabel: 'Maximum cards',
    ShowAudienceHintFieldLabel: 'Show resolved audience tokens',
    // Component strings
    LoadingSpinnerLabel: 'Loading links...',
    LoadingStatePanelTitle: 'Loading',
    LoadingStatePanelMessage: 'Resolving audience and preparing links.',
    ErrorStatePanelTitle: 'Could not load the segmented links.',
    ErrorStatePanelMessage: 'Check the list configuration or try again.',
    PartialDataStatePanelTitle: 'Fallback links have been used.',
    PartialDataStatePanelMessage: 'Some audience signals are missing or part of the catalog is incomplete.',
    EmptyStatePanelTitle: 'No links available for your profile.',
    EmptyStatePanelMessageNoCategory: 'No links for this category. Try another category or clear the filter.',
    EmptyStatePanelMessageDefault: 'No links available for your profile.',
    RetryActionLabel: 'Retry',
    AudienceHintAriaLabel: 'Resolved audience tokens',
    FilterToolbarAriaLabel: 'Filter links by category',
    BadgePersonalizadoLabel: 'Custom',
    BadgeGenericoLabel: 'Generic',
    BadgePartialLabel: 'Partial',
    OpenLinkLabel: 'Open link',
    ContextualNavigationLabel: 'Contextual navigation',
    SourceMetaLabel: 'Source',
    AudienceMetaLabel: 'Audience',
    FooterStatusLabel: 'Status',
    FooterNotesLabel: 'Notes',
    FooterNoIncidenciasLabel: 'no incidents',
    // Hook and service labels
    AllCategoriesLabel: 'All',
    DefaultWebPartTitle: 'Audience quick links',
    LoadingCatalogLabel: 'Loading catalog...',
    LoadingAudienceLabel: 'Resolving from user context',
    NoDataSourceLabel: 'No data available',
    CouldNotResolveAudienceLabel: 'Could not resolve audience',
    AudienceGeneralLabel: 'General audience',
    AudienceHybridPrefix: 'Hybrid audience',
    AudienceNamedPrefix: 'Audience',
    AppLocalEnvironmentSharePoint: 'The app is running on your local environment as SharePoint web part',
    AppLocalEnvironmentTeams: 'The app is running on your local environment as Microsoft Teams app',
    AppLocalEnvironmentOffice: 'The app is running on your local environment in office.com',
    AppLocalEnvironmentOutlook: 'The app is running on your local environment in Outlook',
    AppSharePointEnvironment: 'The app is running on SharePoint page',
    AppTeamsTabEnvironment: 'The app is running in Microsoft Teams',
    AppOfficeEnvironment: 'The app is running in office.com',
    AppOutlookEnvironment: 'The app is running in Outlook',
    UnknownEnvironment: 'The app is running in an unknown environment'
    ErrorBoundaryTitle: "Something went wrong",
    ErrorBoundaryMessage: "This web part encountered an unexpected error. Please reload the page or contact your administrator.",
  };
});
