define([], function () {
  return {
    PropertyPaneDescription: 'Configuración de accesos rápidos por audiencia',
    BasicGroupName: 'Contenido y audiencia',
    TitleFieldLabel: 'Título del web part',
    DescriptionFieldLabel: 'Descripción breve',
    DataSourceTypeFieldLabel: 'Origen de datos',
    SharePointListLabel: 'Lista SharePoint',
    JsonUrlLabel: 'URL JSON (mismo origen)',
    StaticConfigLabel: 'Catálogo interno',
    ListTitleOrUrlFieldLabel: 'Nombre de la lista o URL JSON del mismo origen',
    AudienceModeFieldLabel: 'Modo de audiencia',
    GroupLabel: 'Grupo',
    DepartmentLabel: 'Departamento',
    CountryLabel: 'País',
    RoleLabel: 'Rol',
    HybridLabel: 'Híbrido',
    DefaultCategoryFieldLabel: 'Categoría por defecto',
    MaxItemsFieldLabel: 'Máximo de tarjetas',
    ShowAudienceHintFieldLabel: 'Mostrar tokens de audiencia resueltos',
    // Strings de componentes
    LoadingSpinnerLabel: 'Cargando accesos...',
    LoadingStatePanelTitle: 'Cargando',
    LoadingStatePanelMessage: 'Resolvemos la audiencia y preparamos los accesos.',
    ErrorStatePanelTitle: 'No se han podido cargar los accesos segmentados.',
    ErrorStatePanelMessage: 'Revisa la configuración de la lista o vuelve a intentar la carga.',
    PartialDataStatePanelTitle: 'Se han usado accesos de reserva.',
    PartialDataStatePanelMessage: 'Faltan algunas señales de audiencia o parte del catálogo no está completo.',
    EmptyStatePanelTitle: 'No hay accesos disponibles para tu perfil.',
    EmptyStatePanelMessageNoCategory: 'No hay accesos para esta categoría. Prueba con otra categoría o limpia el filtro.',
    EmptyStatePanelMessageDefault: 'No hay accesos disponibles para tu perfil.',
    RetryActionLabel: 'Reintentar',
    AudienceHintAriaLabel: 'Tokens de audiencia resueltos',
    FilterToolbarAriaLabel: 'Filtrar accesos por categoría',
    BadgePersonalizadoLabel: 'Personalizado',
    BadgeGenericoLabel: 'Genérico',
    BadgePartialLabel: 'Parcial',
    OpenLinkLabel: 'Abrir acceso',
    ContextualNavigationLabel: 'Navegación contextual',
    SourceMetaLabel: 'Fuente',
    AudienceMetaLabel: 'Audiencia',
    FooterStatusLabel: 'Estado',
    FooterNotesLabel: 'Notas',
    FooterNoIncidenciasLabel: 'sin incidencias',
    // Etiquetas de hook y servicio
    AllCategoriesLabel: 'Todas',
    DefaultWebPartTitle: 'Accesos rápidos por audiencia',
    LoadingCatalogLabel: 'Cargando catálogo...',
    LoadingAudienceLabel: 'Resuelto desde el contexto de usuario',
    NoDataSourceLabel: 'Sin datos disponibles',
    CouldNotResolveAudienceLabel: 'No se pudo resolver la audiencia',
    AudienceGeneralLabel: 'Audiencia general',
    AudienceHybridPrefix: 'Audiencia híbrida',
    AudienceNamedPrefix: 'Audiencia',
    AppLocalEnvironmentSharePoint: 'La app se está ejecutando en tu entorno local como web part de SharePoint',
    AppLocalEnvironmentTeams: 'La app se está ejecutando en tu entorno local como app de Microsoft Teams',
    AppLocalEnvironmentOffice: 'La app se está ejecutando en tu entorno local en office.com',
    AppLocalEnvironmentOutlook: 'La app se está ejecutando en tu entorno local en Outlook',
    AppSharePointEnvironment: 'La app se está ejecutando en una página de SharePoint',
    AppTeamsTabEnvironment: 'La app se está ejecutando en Microsoft Teams',
    AppOfficeEnvironment: 'La app se está ejecutando en office.com',
    AppOutlookEnvironment: 'La app se está ejecutando en Outlook',
    UnknownEnvironment: 'La app se está ejecutando en un entorno desconocido'
    ErrorBoundaryTitle: "Se ha producido un error inesperado",
    ErrorBoundaryMessage: "Este web part ha encontrado un error no esperado. Recarga la página o contacta con el administrador."
  };
});
